export const translateRoleBDC = {
  admin: "Modérateur",
  referent: "Référent",
  structure: "Responsable",
  young: "Volontaire HTS",
  young_cle: "Volontaire CLE",
  head_center: "Chef de centre",
  head_center_adjoint: "Chef de centre Adjoint",
  referent_sanitaire: "Référent sanitaire",
  public: "Public",
  visitor: "Visiteur régional",
  dsnj: "DSNJ",
  administrateur_cle_referent_etablissement: "Admin CLE - Chef établissement",
  administrateur_cle_coordinateur_cle: "Admin CLE - Coordinateur",
  referent_classe: "Référent Classe",
};
