version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 350
  method-lines:
    config:
      threshold: 35
  return-statements:
    config:
      threshold: 15
  similar-code:
    config:
      threshold: 150
  identical-code:
    config:
      threshold: 70
