version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 350
  method-lines:
    config:
      threshold: 35
  return-statements:
    config:
      threshold: 15
  similar-code:
    config:
      threshold: 150
  identical-code:
    config:
      threshold: 70
exclude_patterns:
 - "config/"
 - "db/"
 - "dist/"
 - "features/"
 - "**/node_modules/"
 - "script/"
 - "**/spec/"
 - "**/test/"
 - "**/tests/"
 - "Tests/"
 - "**/vendor/"
 - "**/*_test.go"
 - "**/*.d.ts"
 - "**/snu-lib/"
 - "**/*.ts"
 - "snu-lib/"
 - "lib/"
