name: "Docker Build & Publish"
description: "Build & Publish a Docker image to a Container Registry"

inputs:
  username:
    description: "Username for Docker registry"
    required: true
  password:
    description: "Password for Docker registry"
    required: true
  registry:
    description: "Registry endpoint"
    required: true
  image_name:
    description: "Name of the image"
    required: true
  image_tag_stable:
    description: "Stable tag for the image"
    required: false
    default: "latest"
  dockerfile_path:
    description: "Path to the application's Dockerfile"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get commit hash
      id: commit
      uses: prompt/actions-commit-hash@v3

    - name: Get current date
      id: date
      shell: bash
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Login to Docker Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        registry: ${{ inputs.registry }}

    - name: Build the Docker image
      shell: bash
      run: docker build -t ${{ inputs.registry }}/${{ inputs.image_name }}:${{ steps.date.outputs.date }}-${{ steps.commit.outputs.short }} -t ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag_stable }} -f ${{ inputs.dockerfile_path }} .

    - name: Push the Docker Image
      shell: bash
      run: |
        docker push ${{ inputs.registry }}/${{ inputs.image_name }}:${{ steps.date.outputs.date }}-${{ steps.commit.outputs.short }}
        docker push ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag_stable }}
