services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=pass1
      - POSTGRES_DB=ferretdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://user1:pass1@postgres:5432/ferretdb
    depends_on:
      - postgres

volumes:
  pgdata:

networks:
  default:
    name: ferretdb
