export enum CohesionCenterTypologyEnum {
  PUBLIC = "PUBLIC",
  PUBLIC_ETAT = "PUBLIC_ETAT",
  PUBLIC_COLLECTIVITE = "PUBLIC_COLLECTIVITE",
  PRIVE_ASSOCIATION = "PRIVE_ASSOCIATION",
  PRIVE_AUTRE = "PRIVE_AUTRE",
  AUTRE = "AUTRE",
  ENSEIGNEMENT_AGRICOLE = "ENSEIGNEMENT_AGRICOLE",
}

export enum CohesionCenterDomainEnum {
  ETABLISSEMENT = "ETABLISSEMENT",
  VACANCES = "VACANCES",
  FORMATION = "FORMATION",
  EDUCATION = "EDUCATION",
  ADMINISTRATIF = "ADMINISTRATIF",
  AUTRE = "AUTRE",
}
