export enum FeatureFlagName {
  SYNC_APPEL_A_PROJET_CLE = "SYNC_APPEL_A_PROJET_CLE",
  CLE_BEFORE_JULY_15 = "CLE_BEFORE_JULY_15",
  CLE_CLASSE_ADD_COHORT_ENABLED = "CLE_CLASSE_ADD_COHORT_ENABLED",
  INVITE_REFERENT_CLASSE = "INVITE_REFERENT_CLASSE",
  INVITE_REFERENT_CLASSE_EACH_CLASSE_VERIFIED = "INVITE_REFERENT_CLASSE_EACH_CLASSE_VERIFIED",
  CLE_IMPORT_CLASSE_COHORT = "CLE_IMPORT_CLASSE_COHORT",
}
