export const FUNCTIONAL_ERRORS = {
  TOO_MANY_YOUNGS_IN_CLASSE: "TOO_MANY_YOUNGS_IN_CLASSE",
  NO_YOUNG_IN_EXPECTED_STATUS: "NO_YOUNG_IN_EXPECTED_STATUS",
  NO_CLASSE_ID_PROVIDED: "NO_CLASSE_ID_PROVIDED",
  NO_COHORT_CODE_PROVIDED: "NO_COHORT_CODE_PROVIDED",
  CANNOT_BE_ADDED_AS_A_REFERENT_CLASSE: "CANNOT_BE_ADDED_AS_A_REFERENT_CLASSE",
};
