export enum STEPS2023 {
  EMAIL_WAITING_VALIDATION = "EMAIL_WAITING_VALIDATION",
  COORDONNEES = "COORDONNEES",
  CONSENTEMENTS = "CONSENTEMENTS",
  REPRESENTANTS = "REPRESENTANTS",
  DOCUMENTS = "DOCUMENTS",
  CONFIRM = "CONFIRM",
  WAITING_CONSENT = "WAITING_CONSENT",
  DONE = "DONE",
}
