export enum TaskStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum TaskName {
  REFERENTIEL_IMPORT = "REFERENTIEL_IMPORT",
  AFFECTATION_HTS_SIMULATION = "AFFECTATION_HTS_SIMULATION",
  AFFECTATION_HTS_DROMCOM_SIMULATION = "AFFECTATION_HTS_DROMCOM_SIMULATION",
  AFFECTATION_CLE_SIMULATION = "AFFECTATION_CLE_SIMULATION",
  AFFECTATION_CLE_DROMCOM_SIMULATION = "AFFECTATION_CLE_DROMCOM_SIMULATION",
  AFFECTATION_HTS_SIMULATION_VALIDER = "AFFECTATION_HTS_SIMULATION_VALIDER",
  AFFECTATION_HTS_DROMCOM_SIMULATION_VALIDER = "AFFECTATION_HTS_DROMCOM_SIMULATION_VALIDER",
  AFFECTATION_CLE_SIMULATION_VALIDER = "AFFECTATION_CLE_SIMULATION_VALIDER",
  AFFECTATION_CLE_DROMCOM_SIMULATION_VALIDER = "AFFECTATION_CLE_DROMCOM_SIMULATION_VALIDER",
  // Plan marketing
  PLAN_MARKETING_IMPORT_CONTACTS = "PLAN_MARKETING_IMPORT_CONTACTS",
  PLAN_MARKETING_IMPORT_CONTACTS_ET_CREER_LISTE = "PLAN_MARKETING_IMPORT_CONTACTS_ET_CREER_LISTE",
  PLAN_MARKETING_IMPORT_CONTACTS_ET_CREER_LISTE_PUIS_ENVOYER_CAMPAGNE = "PLAN_MARKETING_IMPORT_CONTACTS_ET_CREER_LISTE_PUIS_ENVOYER_CAMPAGNE",
  // Bascule
  BACULE_JEUNES_VALIDES_SIMULATION = "BACULE_JEUNES_VALIDES_SIMULATION",
  BACULE_JEUNES_VALIDES_SIMULATION_VALIDER = "BACULE_JEUNES_VALIDES_SIMULATION_VALIDER",
  BACULE_JEUNES_NONVALIDES_SIMULATION = "BACULE_JEUNES_NONVALIDES_SIMULATION",
  BACULE_JEUNES_NONVALIDES_SIMULATION_VALIDER = "BACULE_JEUNES_NONVALIDES_SIMULATION_VALIDER",
  // Désistement
  DESISTEMENT_POST_AFFECTATION_SIMULATION = "DESISTEMENT_POST_AFFECTATION_SIMULATION",
  DESISTEMENT_POST_AFFECTATION_VALIDER = "DESISTEMENT_POST_AFFECTATION",
}
