export enum TaskStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum TaskName {
  REFERENTIEL_IMPORT = "REFERENTIEL_IMPORT",
  AFFECTATION_HTS_SIMULATION = "AFFECTATION_HTS_SIMULATION",
  AFFECTATION_HTS_SIMULATION_VALIDER = "AFFECTATION_HTS_SIMULATION_VALIDER",
}
