name: "Get custom environment name"
description: "Get the environment name corresponding to a branch"

inputs:
  branch_name:
    description: "Name of the branch"
    required: true

outputs:
  env_name:
    description: "Custom environment name"
    value: ${{ steps.env_name.outputs.env_name }}

runs:
  using: "composite"
  steps:
    - name: Get environment name
      id: env_name
      run: |
        env_name=$(echo ${{ inputs.branch_name }} | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-' | tr -s '-' | cut -c 1-25)
        echo "Environment name: $env_name"
        echo "env_name=$env_name" >> $GITHUB_OUTPUT
