const PHONE_ZONES_NAMES = [
  "FRANCE",
  "GUADELOUPE",
  "GUYANE",
  "LA_REUNION",
  "MARTINIQUE",
  "MAYOTTE",
  "NOUVELLE_CALEDONIE",
  "POLYNESIE_FRANCAISE",
  "SAINT_BARTHELEMY",
  "SAINT_MARTIN",
  "SAINT_PIERRE_ET_MIQUELON",
  "WALLIS_ET_FUTUNA",
  "AUTRE",
];

module.exports = {
  PHONE_ZONES_NAMES,
};
