const PHONE_ZONES_NAMES = {
  FRANCE: "FRANCE",
  GUADELOUPE: "GUADELOUPE",
  GUYANE: "GUYANE",
  LA_REUNION: "LA_REUNION",
  MARTINIQUE: "MARTINIQUE",
  MAYOTTE: "MAYOTTE",
  NOUVELLE_CALEDONIE: "NOUVELLE_CALEDONIE",
  POLYNESIE_FRANCAISE: "POLYNESIE_FRANCAISE",
  SAINT_BARTHELEMY: "SAINT_BARTHELEMY",
  SAINT_MARTIN: "SAINT_MARTIN",
  SAINT_PIERRE_ET_MIQUELON: "SAINT_PIERRE_ET_MIQUELON",
  WALLIS_ET_FUTUNA: "WALLIS_ET_FUTUNA",
  AUTRE: "AUTRE",
};

const PHONE_ZONES_NAMES_ARR = Object.values(PHONE_ZONES_NAMES);

module.exports = {
  PHONE_ZONES_NAMES,
  PHONE_ZONES_NAMES_ARR,
};
