const translateIndexes = (index) => {
  switch (index) {
    case "young":
      return "volontaires";
    case "mission":
      return "Missions";
    case "application":
      return "candidatures";
    default:
      return index;
  }
};

const youngExportFields = [
  {
    id: "identity",
    title: "Identité du volontaire",
    desc: ["Prénom", "Nom", "Sexe", "Cohorte", "Cohorte d'origine"],
    fields: ["firstName", "lastName", "gender", "cohort", "originalCohort"],
  },
  {
    id: "contact",
    title: "Contact du volontaire",
    desc: ["Email", "Téléphone"],
    fields: ["email", "phone", "phoneZone"],
  },
  {
    id: "birth",
    title: "Date et lieu de naissance du volontaire",
    desc: ["Date de naissance", "Pays de naissance", "Ville de naissance", "Code postal de naissance"],
    fields: ["birthdateAt", "birthCountry", "birthCity", "birthCityZip", "latestCNIFileExpirationDate"],
  },
  {
    id: "address",
    title: "Lieu de résidence du volontaire",
    desc: [
      "Adresse postale",
      "Code postal",
      "Ville",
      "Pays",
      "Nom de l'hébergeur",
      "Prénom de l'hébergeur",
      "Lien avec l'hébergeur",
      "Adresse - étranger",
      "Code postal - étranger",
      "Ville - étranger",
      "Pays - étranger",
    ],
    fields: ["address", "zip", "city", "country", "hostLastName", "hostFirstName", "hostRelationship", "foreignAddress", "foreignZip", "foreignCity", "foreignCountry"],
  },
  {
    id: "location",
    title: "Localisation du volontaire",
    desc: ["Département", "Académie", "Région"],
    fields: ["department", "academy", "region"],
  },
  {
    id: "schoolSituation",
    title: "Situation scolaire",
    desc: [
      "Niveau",
      "Type d'établissement",
      "Nom de l'établissement",
      "Code postal de l'établissement",
      "Ville de l'établissement",
      "Département de l'établissement",
      "UAI de l'établissement",
    ],
    fields: ["schoolId", "situation", "grade", "schoolType", "schoolName", "schoolZip", "schoolCity", "schoolDepartment"],
  },
  {
    id: "situation",
    title: "Situation particulière",
    desc: [
      "Quartier Prioritaire de la ville",
      "Zone Rurale",
      "Handicap",
      "PPS",
      "PAI",
      "Aménagement spécifique",
      "Nature de l'aménagement spécifique",
      "Aménagement pour mobilité réduite",
      "Besoin d'être affecté(e) dans le département de résidence",
      "Allergies ou intolérances alimentaires",
      "Activité de haut-niveau",
      "Nature de l'activité de haut-niveau",
      "Activités de haut niveau nécessitant d'être affecté dans le département de résidence",
      "Document activité de haut-niveau",
      "Structure médico-sociale",
      "Nom de la structure médico-sociale",
      "Adresse de la structure médico-sociale",
      "Code postal de la structure médico-sociale",
      "Ville de la structure médico-sociale",
    ],
    fields: [
      "qpv",
      "populationDensity",
      "handicap",
      "ppsBeneficiary",
      "paiBeneficiary",
      "specificAmenagment",
      "specificAmenagmentType",
      "reducedMobilityAccess",
      "handicapInSameDepartment",
      "allergies",
      "highSkilledActivity",
      "highSkilledActivityType",
      "highSkilledActivityInSameDepartment",
      "highSkilledActivityProofFiles",
      "medicosocialStructure",
      "medicosocialStructureName",
      "medicosocialStructureAddress",
      "medicosocialStructureZip",
      "medicosocialStructureCity",
    ],
  },
  {
    id: "representative1",
    title: "Représentant légal 1",
    desc: ["Statut", "Nom", "Prénom", "Email", "Téléphone", "Adresse", "Code postal", "Ville", "Département et région du représentant légal"],
    fields: [
      "parent1Status",
      "parent1FirstName",
      "parent1LastName",
      "parent1Email",
      "parent1Phone",
      "parent1Address",
      "parent1Zip",
      "parent1City",
      "parent1Department",
      "parent1Region",
      "parent1PhoneZone",
    ],
  },
  {
    id: "representative2",
    title: "Représentant légal 2",
    desc: ["Statut", "Nom", "Prénom", "Email", "Téléphone", "Adresse", "Code postal", "Ville", "Département et région du représentant légal"],
    fields: [
      "parent2Status",
      "parent2FirstName",
      "parent2LastName",
      "parent2Email",
      "parent2Phone",
      "parent2Address",
      "parent2Zip",
      "parent2City",
      "parent2Department",
      "parent2Region",
      "parent2PhoneZone",
    ],
  },
  {
    id: "consent",
    title: "Consentement",
    desc: ["Consentement des représentants légaux."],
    fields: ["parentConsentment"],
  },
  {
    id: "status",
    title: "Statut",
    desc: ["Statut général", "Statut phase 1", "Statut phase 2", "Statut phase 3", "Date du dernier statut"],
    fields: ["status", "phase", "statusPhase1", "statusPhase2", "statusPhase3", "lastStatusAt"],
  },
  {
    id: "phase1Affectation",
    title: "Phase 1 - Affectation ",
    desc: ["ID", "Code", "Nom", "Ville", "Département et région du centre"],
    fields: ["cohesionCenterId", "sessionPhase1Id"],
  },
  {
    id: "phase1Transport",
    title: "Phase 1 - Transport",
    desc: [
      "Autonomie",
      "Numéro de bus",
      "Les informations de transports transmises par email",
      "ID du bus",
      "Nom du point de rassemblement",
      "Adresse du point de rassemblement",
      "Ville du point de rassemblement",
      "Dates d'aller et de retour",
      "Heures de départ et de convocation",
      "Heure de retour",
      "Voyage en avion",
    ],
    fields: ["meetingPointId", "ligneId", "transportInfoGivenByLocal", "deplacementPhase1Autonomous", "isTravelingByPlane"],
  },
  {
    id: "phase1DocumentStatus",
    title: "Phase 1 - Statut des documents",
    desc: ["Droit à l'image", "Autotest PCR", "Règlement intérieur", "Fiche sanitaire"],
    fields: ["imageRightFilesStatus", "autoTestPCRFilesStatus", "rulesYoung", "cohesionStayMedicalFileReceived"],
  },
  {
    id: "phase1DocumentAgreement",
    title: "Phase 1 - Accords",
    desc: ["Accords pour droit à l'image et autotests PCR."],
    fields: ["imageRight", "autoTestPCR"],
  },
  {
    id: "phase1Attendance",
    title: "Phase 1 - Présence",
    desc: ["Présence à l'arrivé", "Présence à la JDM", "Date de départ", "Motif de départ", "Commentaire du départ"],
    fields: ["cohesionStayPresence", "presenceJDM", "departSejourAt", "departSejourMotif", "departSejourMotifComment"],
  },
  {
    id: "phase2",
    title: "Phase 2",
    desc: [
      "Domaines MIG 1, MIG 2 et MIG 3",
      "Projet professionnel",
      "Période privilégiée",
      "Choix de périodes",
      "Mobilité",
      "Mobilité autour d'un proche",
      "Information du proche",
      "Mode de transport",
      "Format de mission",
      "Engagement hors SNU",
      "Souhait MIG",
    ],
    fields: [
      "domains",
      "professionnalProject",
      "professionnalProjectPrecision",
      "period",
      "periodRanking",
      "mobilityNearSchool",
      "mobilityNearHome",
      "mobilityNearRelative",
      "mobilityNearRelativeName",
      "mobilityNearRelativeAddress",
      "mobilityNearRelativeZip",
      "mobilityNearRelativeCity",
      "mobilityTransport",
      "missionFormat",
      "engaged",
      "engagedDescription",
      "desiredLocation",
    ],
  },
  {
    id: "accountDetails",
    title: "Compte",
    desc: ["Dates de création, d'édition et de dernière connexion"],
    fields: ["createdAt", "updatedAt", "lastLoginAt"],
  },
  {
    id: "desistement",
    title: "Désistement",
    desc: ["Raison du désistement", "Message de désistement"],
    fields: ["withdrawnReason", "withdrawnMessage"],
  },
  {
    id: "psc1Info",
    title: "Information sur le PSC1",
    desc: ["PSC1"],
    fields: ["psc1Info"],
  },
];

const missionExportFields = [
  {
    id: "missionInfo",
    title: "Informations sur la mission",
    desc: [
      "Titre de la mission",
      "Date du début",
      "Date de fin",
      "Nombre de volontaires recherchés",
      "Places restantes sur la mission",
      "Visibilité de la mission",
      "Source de la mission",
    ],
    fields: ["_id", "name", "startAt", "endAt", "placesTotal", "placesLeft", "visibility", "isJvaMission"],
  },
  {
    id: "status",
    title: "Statut de la mission",
    desc: ["Statut de la mission", "Créée le", "Mise à jour le", "Commentaire sur le statut"],
    fields: ["status", "createdAt", "updatedAt", "statusComment"],
  },
  {
    id: "missionType",
    title: "Type de mission",
    desc: ["Domaine principal de la mission", "Domaine(s) secondaire(s) de la mission", "Préparation militaire"],
    fields: ["mainDomain", "format", "isMilitaryPreparation"],
  },
  {
    id: "missionDetails",
    title: "Détails de la mission",
    desc: ["Objectifs de la mission", "Actions concrètes", "Contraintes", "Durée", "Fréquence estimée", "Période de réalisation", "Hébergement proposé", "Hébergement payant"],
    fields: ["description", "actions", "contraintes", "duration", "frequence", "period", "hebergement", "hebergementPayant"],
  },
  {
    id: "tutor",
    title: "Tuteur de la mission",
    desc: ["Id du tuteur", "Nom du tuteur", "Prénom du tuteur", "Email du tuteur", "Portable du tuteur", "Téléphone du tuteur"],
    fields: ["tutorId"],
  },
  {
    id: "location",
    title: "Localisation de la mission",
    desc: ["Adresse", "Code postal", "Ville", "Département", "Région"],
    fields: ["address", "zip", "city", "department", "region"],
  },
  {
    id: "structureInfo",
    title: "Informations sur la structure",
    desc: ["Id de la structure", "Nom de la structure", "Statut juridique de la structure", "Type de structure", "Sous-type de structure", "Présentation de la structure"],
    fields: ["structureId"],
  },
  {
    id: "structureLocation",
    title: "Localisation de la structure",
    desc: ["Adresse de la structure", "Code postal de la structure", "Ville de la structure", "Département de la structure", "Région de la structure"],
    fields: ["structureId"],
  },
];

const structureExportFields = [
  {
    id: "structureInfo",
    title: "Informations sur la structure",
    desc: ["Nom de la structure", "Statut juridique", "Type de structure", "Sous-type de structure", "Présentation de la structure"],
    fields: ["name", "legalStatus", "types", "sousTypes", "description"],
  },
  {
    id: "location",
    title: "Localisation de la structure",
    desc: ["Adresse de la structure", "Code postal de la structure", "Ville de la structure", "Département de la structure", "Région de la structure"],
    fields: ["address", "zip", "city", "department", "region"],
  },
  {
    id: "details",
    title: "Détails",
    desc: ["Site internet", "Facebook", "Twitter", "Instagram", "Numéro de SIRET"],
    fields: ["website", "facebook", "twitter", "instagram", "siret"],
  },
  {
    id: "network",
    title: "Tête de réseau",
    desc: ["Est une tête de réseau", "Nom de la tête de réseau"],
    fields: ["isNetwork", "networkName"],
  },
  {
    id: "team",
    title: "Equipe",
    desc: [
      "Taille d'équipe",
      "Membre 1 - Nom",
      "Membre 1 - Prénom",
      "Membre 1 - Email",
      "Membre 2 - Nom",
      "Membre 2 - Prénom",
      "Membre 2 - Email",
      "Membre 3 - Nom",
      "Membre 3 - Prénom",
      "Membre 3 - Email",
    ],
    fields: [],
  },
  {
    id: "status",
    title: "Statut",
    desc: ["Créé lé", "Mis à jour le", "Statut général"],

    fields: ["createdAt", "updatedAt", "status"],
  },
];

const applicationExportFieldsStructure = [
  {
    id: "identity",
    title: "Identité du volontaire",
    desc: ["Cohorte", "Prénom", "Nom", "Sexe", "Date de naissance"],
    fields: ["youngCohort", "youngFirstName", "youngLastName", "gender", "youngBirthdateAt"],
  },
  {
    id: "contact",
    title: "Contact du volontaire",
    desc: ["Email", "Téléphone"],
    fields: ["youngId", "youngEmail"],
  },
  {
    id: "address",
    title: "Lieu de résidence du volontaire",
    desc: ["Adresse postale du volontaire", "Code postal du volontaire", "Ville du volontaire", "Pays du volontaire"],
    fields: ["youngId"],
  },
  {
    id: "location",
    title: "Localisation du volontaire",
    desc: ["Département du volontaire", "Académie du volontaire", "Région du volontaire"],
    fields: ["youngId"],
  },
  {
    id: "proche",
    title: "Localisation de l'adresse d'un proche déclaré",
    desc: ["Adresse postale du proche", "Code postal du proche", "Ville du proche"],
    fields: ["mobilityNearRelativeAddress", "mobilityNearRelativeZip", "mobilityNearRelativeCity"],
  },
  {
    id: "application",
    title: "Candidature",
    desc: [
      "Statut de la candidature",
      "Choix - Ordre de la candidature",
      "Candidature créée le",
      "Candidature mise à jour le",
      "Statut du contrat d'engagement",
      "Pièces jointes à l’engagement",
      "Statut du dossier d'éligibilité PM",
    ],
    fields: [
      "youngId",
      "status",
      "priority",
      "createdAt",
      "updatedAt",
      "contractAvenantFiles",
      "justificatifsFiles",
      "feedBackExperienceFiles",
      "othersFiles",
      "contractStatus",
      "eligibilityStatus",
    ],
  },
  {
    id: "missionInfo",
    title: "Informations sur la mission",
    desc: ["ID de la mission", "Titre de la mission", "Date du début", "Date de fin", "Domaine d'action principal", "Préparation militaire"],
    fields: ["missionId"],
  },
  {
    id: "missionTutor",
    title: "Tuteur de la mission",
    desc: ["Nom du tuteur", "Prénom du tuteur", "Email du tuteur", "Portable du tuteur", "Téléphone du tuteur"],
    fields: ["tutorId"],
  },
  {
    id: "missionLocation",
    title: "Localisation de la mission",
    desc: ["Adresse", "Code postal", "Ville", "Département", "Région"],
    fields: ["missionId"],
  },
  {
    id: "structureInfo",
    title: "Informations sur la structure",
    desc: ["Id de la structure", "Nom de la structure", "Statut juridique de la structure", "Type de structure", "Sous-type de structure", "Présentation de la structure"],
    fields: ["structureId"],
  },
  {
    id: "structureLocation",
    title: "Localisation de la structure",
    desc: ["Adresse de la structure", "Code postal de la structure", "Ville de la structure", "Département de la structure", "Région de la structure"],
    fields: ["structureId"],
  },
  {
    id: "status",
    title: "Statut",
    desc: ["Statut général", "Statut phase 2", "Statut de la candidature", "Commentaire sur le statut"],
    fields: ["youngId", "status", "statusComment"],
  },
  {
    id: "choices",
    title: "Préférences de MIG du volontaire",
    desc: [
      "Domaine de MIG 1",
      "Domaine de MIG 2",
      "Domaine de MIG 3",
      "Projet professionnel",
      "Information supplémentaire sur le projet professionnel",
      "Période privilégiée pour réaliser des missions",
      "Choix 1 période",
      "Choix 2 période",
      "Choix 3 période",
      "Choix 4 période",
      "Choix 5 période",
      "Mobilité aux alentours de son établissement",
      "Mobilité aux alentours de son domicile",
      "Mobilité aux alentours d'un de ses proches",
      "Adresse du proche",
      "Mode de transport",
      "Format de mission",
      "Engagement dans une structure en dehors du SNU",
      "Description engagement ",
      "Souhait MIG",
    ],
    fields: ["youngId", "professionnalProjectPrecision", "period"],
  },
  {
    id: "representative1",
    title: "Représentant légal 1",
    desc: [
      "Statut représentant légal 1",
      "Prénom représentant légal 1",
      "Nom représentant légal 1",
      "Email représentant légal 1",
      "Téléphone représentant légal 1",
      "Adresse représentant légal 1",
      "Code postal représentant légal 1",
      "Ville représentant légal 1",
      "Département représentant légal 1",
      "Région représentant légal 1",
    ],
    fields: ["youngId"],
  },
  {
    id: "representative2",
    title: "Représentant légal 2",
    desc: [
      "Statut représentant légal 2",
      "Prénom représentant légal 2",
      "Nom représentant légal 2",
      "Email représentant légal 2",
      "Téléphone représentant légal 2",
      "Adresse représentant légal 2",
      "Code postal représentant légal 2",
      "Ville représentant légal 2",
      "Département représentant légal 2",
      "Région représentant légal 2",
    ],
    fields: ["youngId"],
  },
];

const applicationExportFields = [
  {
    id: "identity",
    title: "Identité du volontaire",
    desc: ["Cohorte", "Prénom", "Nom", "Sexe", "Date de naissance"],
    fields: ["youngId", "youngCohort", "youngFirstName", "youngLastName", "youngBirthdateAt"],
  },
  {
    id: "contact",
    title: "Contact du volontaire",
    desc: ["Email", "Téléphone"],
    fields: ["youngId", "youngEmail"],
  },
  {
    id: "address",
    title: "Lieu de résidence du volontaire",
    desc: ["Issu de QPV", "Adresse postale du volontaire", "Code postal du volontaire", "Ville du volontaire", "Pays du volontaire"],
    fields: ["youngId"],
  },
  {
    id: "location",
    title: "Localisation du volontaire",
    desc: ["Département du volontaire", "Académie du volontaire", "Région du volontaire"],
    fields: ["youngId"],
  },
  {
    id: "application",
    title: "Candidature",
    desc: [
      "Statut de la candidature",
      "Choix - Ordre de la candidature",
      "Candidature créée le",
      "Candidature mise à jour le",
      "Statut du contrat d'engagement",
      "Pièces jointes à l’engagement",
      "Statut du dossier d'éligibilité PM",
    ],
    fields: ["youngId", "status", "priority", "createdAt", "updatedAt", "contractAvenantFiles", "justificatifsFiles", "feedBackExperienceFiles", "othersFiles", "contractStatus"],
  },
  {
    id: "missionInfo",
    title: "Informations sur la mission",
    desc: ["ID de la mission", "Titre de la mission", "Date du début", "Date de fin", "Domaine d'action principal", "Préparation militaire"],
    fields: ["missionId"],
  },
  {
    id: "missionTutor",
    title: "Tuteur de la mission",
    desc: ["Nom du tuteur", "Prénom du tuteur", "Email du tuteur", "Portable du tuteur", "Téléphone du tuteur"],
    fields: ["tutorId"],
  },
  {
    id: "missionLocation",
    title: "Localisation de la mission",
    desc: ["Adresse", "Code postal", "Ville", "Département", "Région"],
    fields: ["missionId"],
  },
  {
    id: "structureInfo",
    title: "Informations sur la structure",
    desc: ["Id de la structure", "Nom de la structure", "Statut juridique de la structure", "Type de structure", "Sous-type de structure", "Présentation de la structure"],
    fields: ["structureId"],
  },
  {
    id: "structureLocation",
    title: "Localisation de la structure",
    desc: ["Adresse de la structure", "Code postal de la structure", "Ville de la structure", "Département de la structure", "Région de la structure"],
    fields: ["structureId"],
  },
  {
    id: "status",
    title: "Statut",
    desc: ["Statut général", "Statut phase 2", "Statut de la candidature"],
    fields: ["youngId", "status"],
  },
  {
    id: "choices",
    title: "Préférences de MIG du volontaire",
    desc: [
      "Domaine de MIG 1",
      "Domaine de MIG 2",
      "Domaine de MIG 3",
      "Projet professionnel",
      "Information supplémentaire sur le projet professionnel",
      "Période privilégiée pour réaliser des missions",
      "Choix 1 période",
      "Choix 2 période",
      "Choix 3 période",
      "Choix 4 période",
      "Choix 5 période",
      "Mobilité aux alentours de son établissement",
      "Mobilité aux alentours de son domicile",
      "Mobilité aux alentours d'un de ses proches",
      "Adresse du proche",
      "Mode de transport",
      "Format de mission",
      "Engagement dans une structure en dehors du SNU",
      "Description engagement ",
      "Souhait MIG",
    ],
    fields: ["youngId", "professionnalProjectPrecision", "period"],
  },
  {
    id: "representative1",
    title: "Représentant légal 1",
    desc: [
      "Statut représentant légal 1",
      "Prénom représentant légal 1",
      "Nom représentant légal 1",
      "Email représentant légal 1",
      "Téléphone représentant légal 1",
      "Adresse représentant légal 1",
      "Code postal représentant légal 1",
      "Ville représentant légal 1",
      "Département représentant légal 1",
      "Région représentant légal 1",
    ],
    fields: ["youngId"],
  },
  {
    id: "representative2",
    title: "Représentant légal 2",
    desc: [
      "Statut représentant légal 2",
      "Prénom représentant légal 2",
      "Nom représentant légal 2",
      "Email représentant légal 2",
      "Téléphone représentant légal 2",
      "Adresse représentant légal 2",
      "Code postal représentant légal 2",
      "Ville représentant légal 2",
      "Département représentant légal 2",
      "Région représentant légal 2",
    ],
    fields: ["youngId"],
  },
];

const youngPlanDeTranportExportFields = [
  {
    id: "identity",
    title: "Identité du volontaire",
    desc: ["Prénom", "Nom", "Sexe", "Cohorte", "Cohorte d'origine"],
    fields: ["firstName", "lastName", "gender", "cohort", "originalCohort"],
  },
  {
    id: "contact",
    title: "Contact du volontaire",
    desc: ["Email", "Téléphone"],
    fields: ["email", "phone", "phoneZone"],
  },
  {
    id: "location",
    title: "Localisation du volontaire",
    desc: ["Département", "Académie", "Région"],
    fields: ["department", "academy", "region"],
  },
  {
    id: "representative1",
    title: "Représentant légal 1",
    desc: ["Statut", "Nom", "Prénom", "Email", "Téléphone", "Adresse", "Code postal", "Ville", "Département et région du représentant légal"],
    fields: [
      "parent1Status",
      "parent1FirstName",
      "parent1LastName",
      "parent1Email",
      "parent1Phone",
      "parent1PhoneZone",
      "parent1Address",
      "parent1Zip",
      "parent1City",
      "parent1Department",
      "parent1Region",
    ],
  },
  {
    id: "representative2",
    title: "Représentant légal 2",
    desc: ["Statut", "Nom", "Prénom", "Email", "Téléphone", "Adresse", "Code postal", "Ville", "Département et région du représentant légal"],
    fields: [
      "parent2Status",
      "parent2FirstName",
      "parent2LastName",
      "parent2Email",
      "parent2Phone",
      "parent2PhoneZone",
      "parent2Address",
      "parent2Zip",
      "parent2City",
      "parent2Department",
      "parent2Region",
    ],
  },
  {
    id: "phase1Affectation",
    title: "Phase 1 - Affectation ",
    desc: ["ID", "Code", "Nom", "Ville", "Département et région du centre"],
    fields: ["sessionPhase1Id"],
  },
  {
    id: "phase1Transport",
    title: "Phase 1 - Transport",
    desc: [
      "ID du transport",
      "ID du point de rassemblement",
      "Nom du point de rassemblement",
      "Adresse du point de rassemblement",
      "Ville du point de rassemblement",
      "Département du point de rassemblement",
      "Région du point de rassemblement",
      "Date et heure de départ (Aller)",
      "Date et heure d'arrivée (Retour)",
    ],
    fields: ["ligneId", "meetingPointId"],
  },
  {
    id: "status",
    title: "Statut",
    desc: ["Statut général", "Statut phase 1", "Droit à l'image"],
    fields: ["status", "statusPhase1", "parent1AllowImageRights"],
  },
];

const missionCandidatureExportFields = [
  {
    id: "identity",
    title: "Identité du volontaire",
    desc: ["Prénom", "Nom", "Sexe", "Cohorte", "Cohorte d'origine"],
    fields: ["firstName", "lastName", "gender", "cohort", "originalCohort"],
  },
  {
    id: "contact",
    title: "Contact du volontaire",
    desc: ["Email", "Téléphone"],
    fields: ["email", "phone"],
  },
  {
    id: "imageRight",
    title: "Droit à l'image",
    desc: ["Droit à l'image"],
    fields: ["imageRight"],
  },
  {
    id: "address",
    title: "Lieu de résidence du volontaire",
    desc: ["Issu de QPV", "Adresse", "Code postal", "Ville", "Pays"],
    fields: ["qpv", "address", "zip", "city", "country"],
  },
  {
    id: "location",
    title: "Localisation du volontaire",
    desc: ["Département", "Académie", "Région"],
    fields: ["department", "academy", "region"],
  },
  {
    id: "application",
    title: "Candidature",
    desc: [
      "Statut de la candidature",
      "Choix - Ordre de la candidature",
      "Candidature créée le",
      "Candidature mise à jour le",
      "Statut du contrat d'engagement",
      "Pièces jointes à l’engagement",
      "Statut du dossier d'éligibilité PM",
    ],
    fields: [
      "youngId",
      "status",
      "priority",
      "createdAt",
      "updatedAt",
      "contractAvenantFiles",
      "justificatifsFiles",
      "feedBackExperienceFiles",
      "othersFiles",
      "missionId",
      "contractStatus",
      "eligibilityStatus",
    ],
  },
  {
    id: "missionInfo",
    title: "Informations sur la mission",
    desc: ["ID de la mission", "Titre de la mission", "Date du début", "Date de fin", "Domaine d'action principal", "Préparation militaire"],
    fields: ["_id", "name", "startAt", "endAt", "mainDomain", "isMilitaryPreparation"],
  },
  {
    id: "missionTutor",
    title: "Tuteur de la mission",
    desc: ["Nom du tuteur", "Prénom du tuteur", "Email du tuteur", "Portable du tuteur", "Téléphone du tuteur"],
    fields: ["tutorId", "firstName", "lastName", "email", "phone", "mobile"],
  },
  {
    id: "missionlocation",
    title: "Localisation de la mission",
    desc: ["Adresse de la mission", "Code postal de la mission", "Ville de la mission", "Département de la mission", "Région de la mission"],
    fields: ["address", "zip", "city", "department", "region"],
  },
  {
    id: "structureInfo",
    title: "Informations sur la structure",
    desc: ["Id de la structure", "Nom de la structure", "Statut juridique de la structure", "Type de structure", "Sous-type de structure", "Présentation de la structure"],
    fields: ["structureId", "name", "types", "legalStatus", "sousType", "description"],
  },
  {
    id: "structureLocation",
    title: "Localisation de la structure",
    desc: ["Adresse de la structure", "Code postal de la structure", "Ville de la structure", "Département de la structure", "Région de la structure"],
    fields: ["structureId", "address", "zip", "city", "department", "region"],
  },
  {
    id: "status",
    title: "Statut",
    desc: ["Statut général", "Statut phase 2", "Droit à l'image"],
    fields: ["status", "statusPhase2", "lastStatusAt"],
  },
  {
    id: "representative1",
    title: "Représentant légal 1",
    desc: ["Statut", "Nom", "Prénom", "Email", "Téléphone", "Adresse", "Code postal", "Ville", "Département et région du représentant légal"],
    fields: [
      "parent1Status",
      "parent1FirstName",
      "parent1LastName",
      "parent1Email",
      "parent1Phone",
      "parent1Address",
      "parent1Zip",
      "parent1City",
      "parent1Department",
      "parent1Region",
    ],
  },
  {
    id: "representative2",
    title: "Représentant légal 2",
    desc: ["Statut", "Nom", "Prénom", "Email", "Téléphone", "Adresse", "Code postal", "Ville", "Département et région du représentant légal"],
    fields: [
      "parent2Status",
      "parent2FirstName",
      "parent2LastName",
      "parent2Email",
      "parent2Phone",
      "parent2Address",
      "parent2Zip",
      "parent2City",
      "parent2Department",
      "parent2Region",
    ],
  },
];

const youngCleExportFields = [
  {
    id: "identity",
    title: "Identité du volontaire",
    desc: ["Prénom", "Nom", "Sexe", "Cohorte", "Cohorte d'origine"],
    fields: ["firstName", "lastName", "gender", "cohort", "originalCohort"],
  },
  {
    id: "contact",
    title: "Contact du volontaire",
    desc: ["Email", "Téléphone"],
    fields: ["email", "phone", "phoneZone"],
  },
  {
    id: "birth",
    title: "Date et lieu de naissance du volontaire",
    desc: ["Date de naissance", "Pays de naissance", "Ville de naissance", "Code postal de naissance"],
    fields: ["birthdateAt", "birthCountry", "birthCity", "birthCityZip", "latestCNIFileExpirationDate"],
  },
  {
    id: "address",
    title: "Lieu de résidence du volontaire",
    desc: [
      "Adresse postale",
      "Code postal",
      "Ville",
      "Pays",
      "Nom de l'hébergeur",
      "Prénom de l'hébergeur",
      "Lien avec l'hébergeur",
      "Adresse - étranger",
      "Code postal - étranger",
      "Ville - étranger",
      "Pays - étranger",
    ],
    fields: ["address", "zip", "city", "country", "hostLastName", "hostFirstName", "hostRelationship", "foreignAddress", "foreignZip", "foreignCity", "foreignCountry"],
  },
  {
    id: "location",
    title: "Localisation du volontaire",
    desc: ["Département", "Région"],
    fields: ["department", "region"],
  },
  {
    id: "etablissement",
    title: "Situation scolaire",
    desc: [
      "Situation du jeune",
      "Niveau du jeune",
      "Type d'établissement",
      "Filère de l'établissement",
      "Nom de l'établissement",
      "Code postal de l'établissement",
      "Ville de l'établissement",
      "Département de l'établissement",
      "UAI de l'établissement",
    ],
    fields: ["etablissementId", "situation", "grade"],
  },
  {
    id: "classe",
    title: "Classe engagée",
    desc: ["Identifiant de la classe", "Nom de la classe", "Coloration de la classe", "Type de la classe", "Filière de la classe", "Niveau de la classe"],
    fields: ["classeId"],
  },
  {
    id: "situation",
    title: "Situation particulière",
    desc: [
      "Quartier Prioritaire de la ville",
      "Zone Rurale",
      "Handicap",
      "PPS",
      "PAI",
      "Aménagement spécifique",
      "Nature de l'aménagement spécifique",
      "Aménagement pour mobilité réduite",
      "Besoin d'être affecté(e) dans le département de résidence",
      "Allergies ou intolérances alimentaires",
      "Activité de haut-niveau",
      "Nature de l'activité de haut-niveau",
      "Activités de haut niveau nécessitant d'être affecté dans le département de résidence",
      "Document activité de haut-niveau",
      "Structure médico-sociale",
      "Nom de la structure médico-sociale",
      "Adresse de la structure médico-sociale",
      "Code postal de la structure médico-sociale",
      "Ville de la structure médico-sociale",
    ],
    fields: [
      "qpv",
      "populationDensity",
      "handicap",
      "ppsBeneficiary",
      "paiBeneficiary",
      "specificAmenagment",
      "specificAmenagmentType",
      "reducedMobilityAccess",
      "handicapInSameDepartment",
      "allergies",
      "highSkilledActivity",
      "highSkilledActivityType",
      "highSkilledActivityInSameDepartment",
      "highSkilledActivityProofFiles",
      "medicosocialStructure",
      "medicosocialStructureName",
      "medicosocialStructureAddress",
      "medicosocialStructureZip",
      "medicosocialStructureCity",
    ],
  },
  {
    id: "representative1",
    title: "Représentant légal 1",
    desc: ["Statut", "Nom", "Prénom", "Email", "Téléphone", "Adresse", "Code postal", "Ville", "Département et région du représentant légal"],
    fields: [
      "parent1Status",
      "parent1FirstName",
      "parent1LastName",
      "parent1Email",
      "parent1Phone",
      "parent1Address",
      "parent1Zip",
      "parent1City",
      "parent1Department",
      "parent1Region",
      "parent1PhoneZone",
    ],
  },
  {
    id: "representative2",
    title: "Représentant légal 2",
    desc: ["Statut", "Nom", "Prénom", "Email", "Téléphone", "Adresse", "Code postal", "Ville", "Département et région du représentant légal"],
    fields: [
      "parent2Status",
      "parent2FirstName",
      "parent2LastName",
      "parent2Email",
      "parent2Phone",
      "parent2Address",
      "parent2Zip",
      "parent2City",
      "parent2Department",
      "parent2Region",
      "parent2PhoneZone",
    ],
  },
  {
    id: "consent",
    title: "Consentement",
    desc: ["Consentement des représentants légaux."],
    fields: ["parentConsentment"],
  },
  {
    id: "status",
    title: "Statut",
    desc: ["Statut général", "Statut phase 1"],
    fields: ["status", "statusPhase1"],
  },
  {
    id: "phase1Affectation",
    title: "Phase 1 - Affectation ",
    desc: ["ID", "Code", "Nom", "Ville", "Département et région du centre"],
    fields: ["cohesionCenterId", "sessionPhase1Id"],
  },
  {
    id: "phase1Transport",
    title: "Phase 1 - Transport",
    desc: [
      "Autonomie",
      "Numéro de bus",
      "Les informations de transports transmises par email",
      "ID du bus",
      "Nom du point de rassemblement",
      "Adresse du point de rassemblement",
      "Ville du point de rassemblement",
      "Dates d'aller et de retour",
      "Heures de départ et de convocation",
      "Heure de retour",
      "Voyage en avion",
    ],
    fields: ["meetingPointId", "ligneId", "transportInfoGivenByLocal", "deplacementPhase1Autonomous", "isTravelingByPlane"],
  },
  {
    id: "phase1DocumentStatus",
    title: "Phase 1 - Statut des documents",
    desc: ["Droit à l'image", "Autotest PCR", "Règlement intérieur", "Fiche sanitaire"],
    fields: ["imageRightFilesStatus", "autoTestPCRFilesStatus", "rulesYoung", "cohesionStayMedicalFileReceived"],
  },
  {
    id: "phase1DocumentAgreement",
    title: "Phase 1 - Accords",
    desc: ["Accords pour droit à l'image et autotests PCR."],
    fields: ["imageRight", "autoTestPCR"],
  },
  {
    id: "phase1Attendance",
    title: "Phase 1 - Présence",
    desc: ["Présence à l'arrivé", "Présence à la JDM", "Date de départ", "Motif de départ", "Commentaire du départ"],
    fields: ["cohesionStayPresence", "presenceJDM", "departSejourAt", "departSejourMotif", "departSejourMotifComment"],
  },
  {
    id: "accountDetails",
    title: "Compte",
    desc: ["Dates de création, d'édition et de dernière connexion"],
    fields: ["createdAt", "updatedAt", "lastLoginAt"],
  },
];

export {
  translateIndexes,
  youngExportFields,
  missionExportFields,
  structureExportFields,
  applicationExportFields,
  youngPlanDeTranportExportFields,
  missionCandidatureExportFields,
  applicationExportFieldsStructure,
  youngCleExportFields,
};
