const departmentToAcademy = {
  Allier: "Clermont-Ferrand",
  Cantal: "Clermont-Ferrand",
  "Haute-Loire": "Clermont-Ferrand",
  "Puy-de-Dôme": "Clermont-Ferrand",
  Ardèche: "Grenoble",
  Drôme: "Grenoble",
  Isère: "Grenoble",
  Savoie: "Grenoble",
  "Haute-Savoie": "Grenoble",
  Ain: "Lyon",
  Loire: "Lyon",
  Rhône: "Lyon",
  Doubs: "Besançon",
  Jura: "Besançon",
  "Haute-Saône": "Besançon",
  "Territoire de Belfort": "Besançon",
  "Côte-d'Or": "Dijon",
  Nièvre: "Dijon",
  "Saône-et-Loire": "Dijon",
  Yonne: "Dijon",
  "Côtes-d'Armor": "Rennes",
  Finistère: "Rennes",
  "Ille-et-Vilaine": "Rennes",
  Morbihan: "Rennes",
  Cher: "Orléans-Tours",
  "Eure-et-Loir": "Orléans-Tours",
  Indre: "Orléans-Tours",
  "Indre-et-Loire": "Orléans-Tours",
  "Loir-et-Cher": "Orléans-Tours",
  Loiret: "Orléans-Tours",
  "Corse-du-Sud": "Corse",
  "Haute-Corse": "Corse",
  "Meurthe-et-Moselle": "Nancy-Metz",
  Meuse: "Nancy-Metz",
  Moselle: "Nancy-Metz",
  Vosges: "Nancy-Metz",
  Ardennes: "Reims",
  Aube: "Reims",
  Marne: "Reims",
  "Haute-Marne": "Reims",
  "Bas-Rhin": "Strasbourg",
  "Haut-Rhin": "Strasbourg",
  Aisne: "Amiens",
  Oise: "Amiens",
  Somme: "Amiens",
  Nord: "Lille",
  "Pas-de-Calais": "Lille",
  "Seine-et-Marne": "Créteil",
  "Seine-Saint-Denis": "Créteil",
  "Val-de-Marne": "Créteil",
  Paris: "Paris",
  Yvelines: "Versailles",
  Essonne: "Versailles",
  "Hauts-de-Seine": "Versailles",
  "Val-d'Oise": "Versailles",
  Calvados: "Normandie",
  Eure: "Normandie",
  Manche: "Normandie",
  Orne: "Normandie",
  "Seine-Maritime": "Normandie",
  Dordogne: "Bordeaux",
  Gironde: "Bordeaux",
  Landes: "Bordeaux",
  "Lot-et-Garonne": "Bordeaux",
  "Pyrénées-Atlantiques": "Bordeaux",
  Corrèze: "Limoges",
  Creuse: "Limoges",
  "Haute-Vienne": "Limoges",
  Charente: "Poitiers",
  "Charente-Maritime": "Poitiers",
  "Deux-Sèvres": "Poitiers",
  Vienne: "Poitiers",
  Aude: "Montpellier",
  Gard: "Montpellier",
  Hérault: "Montpellier",
  Lozère: "Montpellier",
  "Pyrénées-Orientales": "Montpellier",
  Ariège: "Toulouse",
  Aveyron: "Toulouse",
  "Haute-Garonne": "Toulouse",
  Gers: "Toulouse",
  Lot: "Toulouse",
  "Hautes-Pyrénées": "Toulouse",
  Tarn: "Toulouse",
  "Tarn-et-Garonne": "Toulouse",
  "Loire-Atlantique": "Nantes",
  "Maine-et-Loire": "Nantes",
  Mayenne: "Nantes",
  Sarthe: "Nantes",
  Vendée: "Nantes",
  "Alpes-de-Haute-Provence": "Aix-Marseille",
  "Hautes-Alpes": "Aix-Marseille",
  "Bouches-du-Rhône": "Aix-Marseille",
  Vaucluse: "Aix-Marseille",
  "Alpes-Maritimes": "Nice",
  Var: "Nice",
  Guadeloupe: "Guadeloupe",
  Martinique: "Martinique",
  Mayotte: "Mayotte",
  Guyane: "Guyane",
  "La Réunion": "La Réunion",
  "Nouvelle-Calédonie": "Nouvelle-Calédonie",
  "Polynésie française": "Polynésie française",
  "Wallis-et-Futuna": "Wallis-et-Futuna",
  "Saint-Pierre-et-Miquelon": "Saint-Pierre-et-Miquelon",
};
const academyToDepartments = {
  "Clermont-Ferrand": ["Allier", "Cantal", "Haute-Loire", "Puy-de-Dôme"],
  Grenoble: ["Ardèche", "Drôme", "Isère", "Savoie", "Haute-Savoie"],
  Lyon: ["Ain", "Loire", "Rhône"],
  Besançon: ["Doubs", "Jura", "Haute-Saône", "Territoire de Belfort"],
  Dijon: ["Côte-d'Or", "Nièvre", "Saône-et-Loire", "Yonne"],
  Rennes: ["Côtes-d'Armor", "Finistère", "Ille-et-Vilaine", "Morbihan"],
  "Orléans-Tours": [
    "Cher",
    "Eure-et-Loir",
    "Indre",
    "Indre-et-Loire",
    "Loir-et-Cher",
    "Loiret",
  ],
  Corse: ["Corse-du-Sud", "Haute-Corse"],
  "Nancy-Metz": ["Meurthe-et-Moselle", "Meuse", "Moselle", "Vosges"],
  Reims: ["Ardennes", "Aube", "Marne", "Haute-Marne"],
  Strasbourg: ["Bas-Rhin", "Haut-Rhin"],
  Amiens: ["Aisne", "Oise", "Somme"],
  Lille: ["Nord", "Pas-de-Calais"],
  Créteil: ["Seine-et-Marne", "Seine-Saint-Denis", "Val-de-Marne"],
  Paris: ["Paris"],
  Versailles: ["Yvelines", "Essonne", "Hauts-de-Seine", "Val-d'Oise"],
  Normandie: ["Calvados", "Eure", "Manche", "Orne", "Seine-Maritime"],
  Bordeaux: [
    "Dordogne",
    "Gironde",
    "Landes",
    "Lot-et-Garonne",
    "Pyrénées-Atlantiques",
  ],
  Limoges: ["Corrèze", "Creuse", "Haute-Vienne"],
  Poitiers: ["Charente", "Charente-Maritime", "Deux-Sèvres", "Vienne"],
  Montpellier: ["Aude", "Gard", "Hérault", "Lozère", "Pyrénées-Orientales"],
  Toulouse: [
    "Ariège",
    "Aveyron",
    "Haute-Garonne",
    "Gers",
    "Lot",
    "Hautes-Pyrénées",
    "Tarn",
    "Tarn-et-Garonne",
  ],
  Nantes: ["Loire-Atlantique", "Maine-et-Loire", "Mayenne", "Sarthe", "Vendée"],
  "Aix-Marseille": [
    "Alpes-de-Haute-Provence",
    "Hautes-Alpes",
    "Bouches-du-Rhône",
    "Vaucluse",
  ],
  Nice: ["Alpes-Maritimes", "Var"],
  Guadeloupe: "Guadeloupe",
  Martinique: "Martinique",
  Mayotte: "Mayotte",
  Guyane: "Guyane",
  "La Réunion": "La Réunion",
  "Nouvelle-Calédonie": "Nouvelle-Calédonie",
  "Polynésie française": "Polynésie française",
  "Wallis-et-Futuna": "Wallis-et-Futuna",
  "Saint-Pierre-et-Miquelon": "Saint-Pierre-et-Miquelon",
};

const academyList = [...new Set(Object.values(departmentToAcademy))];

module.exports = { departmentToAcademy, academyList, academyToDepartments };
