const departmentToAcademy = {
  Allier: "Clermont-Ferrand",
  Cantal: "Clermont-Ferrand",
  "Haute-Loire": "Clermont-Ferrand",
  "Puy-de-Dôme": "Clermont-Ferrand",
  Ardèche: "Grenoble",
  Drôme: "Grenoble",
  Isère: "Grenoble",
  Savoie: "Grenoble",
  "Haute-Savoie": "Grenoble",
  Ain: "Lyon",
  Loire: "Lyon",
  Rhône: "Lyon",
  Doubs: "Besançon",
  Jura: "Besançon",
  "Haute-Saône": "Besançon",
  "Territoire de Belfort": "Besançon",
  "Côte-d'Or": "Dijon",
  Nièvre: "Dijon",
  "Saône-et-Loire": "Dijon",
  Yonne: "Dijon",
  "Côtes-d'Armor": "Rennes",
  Finistère: "Rennes",
  "Ille-et-Vilaine": "Rennes",
  Morbihan: "Rennes",
  Cher: "Orléans-Tours",
  "Eure-et-Loir": "Orléans-Tours",
  Indre: "Orléans-Tours",
  "Indre-et-Loire": "Orléans-Tours",
  "Loir-et-Cher": "Orléans-Tours",
  Loiret: "Orléans-Tours",
  "Corse-du-Sud": "Corse",
  "Haute-Corse": "Corse",
  "Meurthe-et-Moselle": "Nancy-Metz",
  Meuse: "Nancy-Metz",
  Moselle: "Nancy-Metz",
  Vosges: "Nancy-Metz",
  Ardennes: "Reims",
  Aube: "Reims",
  Marne: "Reims",
  "Haute-Marne": "Reims",
  "Bas-Rhin": "Strasbourg",
  "Haut-Rhin": "Strasbourg",
  Aisne: "Amiens",
  Oise: "Amiens",
  Somme: "Amiens",
  Nord: "Lille",
  "Pas-de-Calais": "Lille",
  "Seine-et-Marne": "Créteil",
  "Seine-Saint-Denis": "Créteil",
  "Val-de-Marne": "Créteil",
  Paris: "Paris",
  Yvelines: "Versailles",
  Essonne: "Versailles",
  "Hauts-de-Seine": "Versailles",
  "Val-d'Oise": "Versailles",
  Calvados: "Normandie",
  Eure: "Normandie",
  Manche: "Normandie",
  Orne: "Normandie",
  "Seine-Maritime": "Normandie",
  Dordogne: "Bordeaux",
  Gironde: "Bordeaux",
  Landes: "Bordeaux",
  "Lot-et-Garonne": "Bordeaux",
  "Pyrénées-Atlantiques": "Bordeaux",
  Corrèze: "Limoges",
  Creuse: "Limoges",
  "Haute-Vienne": "Limoges",
  Charente: "Poitiers",
  "Charente-Maritime": "Poitiers",
  "Deux-Sèvres": "Poitiers",
  Vienne: "Poitiers",
  Aude: "Montpellier",
  Gard: "Montpellier",
  Hérault: "Montpellier",
  Lozère: "Montpellier",
  "Pyrénées-Orientales": "Montpellier",
  Ariège: "Toulouse",
  Aveyron: "Toulouse",
  "Haute-Garonne": "Toulouse",
  Gers: "Toulouse",
  Lot: "Toulouse",
  "Hautes-Pyrénées": "Toulouse",
  Tarn: "Toulouse",
  "Tarn-et-Garonne": "Toulouse",
  "Loire-Atlantique": "Nantes",
  "Maine-et-Loire": "Nantes",
  Mayenne: "Nantes",
  Sarthe: "Nantes",
  Vendée: "Nantes",
  "Alpes-de-Haute-Provence": "Aix-Marseille",
  "Hautes-Alpes": "Aix-Marseille",
  "Bouches-du-Rhône": "Aix-Marseille",
  Vaucluse: "Aix-Marseille",
  "Alpes-Maritimes": "Nice",
  Var: "Nice",
  Guadeloupe: "Région académique",
  Martinique: "Région académique",
  Mayotte: "Région académique",
  Guyane: "Région académique",
  "La Réunion": "Région académique",
  "Nouvelle-Calédonie": "Vice-rectorat",
  "Polynésie française": "Vice-rectorat",
  "Wallis-et-Futuna": "Vice-rectorat",
  "Saint-Pierre-et-Miquelon": "Service de l'Education",
};

module.exports = { departmentToAcademy };
