const PHASE_STATUS_COLOR = {
  VALIDATED: "#6CC763",
  DONE: "#6CC763",
  CANCEL: "#FE7B52",
  IN_PROGRESS: "#5145cd",
  AFFECTED: "#5145cd",
  WITHDRAWN: "#BE3B12",
  WAITING_ACCEPTATION: "#FEB951",
};

const APPLICATION_STATUS_COLORS = {
  WAITING_VALIDATION: "#FE7B52",
  WAITING_VERIFICATION: "#FE7B52",
  WAITING_ACCEPTATION: "#FEB951",
  VALIDATED: "#6CC763",
  DONE: "#1C7713",
  REFUSED: "#F8A9AD",
  CANCEL: "#ffa987",
  IN_PROGRESS: "#382F79",
  ABANDON: "#BE3B12",
};

const YOUNG_STATUS_COLORS = {
  WAITING_VALIDATION: "#FE7B52",
  WAITING_CORRECTION: "#FEB951",
  VALIDATED: "#6CC763",
  REFUSED: "#F8A9AD",
  IN_PROGRESS: "#382F79",
  WITHDRAWN: "#884500",
  WAITING_REALISATION: "#FE7B52",
  AFFECTED: "#382F79",
  WAITING_AFFECTATION: "#FEB951",
  WAITING_ACCEPTATION: "#FEB951",
  CANCEL: "#FE7B52",
  DONE: "#6CC763",
  NOT_DONE: "#EF4036",
};

const MISSION_STATUS_COLORS = {
  WAITING_VALIDATION: "#FE7B52",
  WAITING_CORRECTION: "#FEB951",
  VALIDATED: "#6CC763",
  DRAFT: "#d9bb71",
  REFUSED: "#F8A9AD",
  CANCEL: "#ffa987",
  ARCHIVED: "#ffb3fb",
};

const STRUCTURE_STATUS_COLORS = {
  WAITING_VALIDATION: "#FE7B52",
  WAITING_CORRECTION: "#FEB951",
  VALIDATED: "#6CC763",
  DRAFT: "#d9bb71",
};

const CONTRACT_STATUS_COLORS = {
  DRAFT: "#FEB951",
  SENT: "#FE7B52",
  VALIDATED: "#6CC763",
};

module.exports = {
  PHASE_STATUS_COLOR,
  APPLICATION_STATUS_COLORS,
  YOUNG_STATUS_COLORS,
  MISSION_STATUS_COLORS,
  STRUCTURE_STATUS_COLORS,
  CONTRACT_STATUS_COLORS,
};
