export const YOUNG_STATUS = {
  WAITING_VALIDATION: 'WAITING_VALIDATION',
  WAITING_CORRECTION: 'WAITING_CORRECTION',
  VALIDATED: 'VALIDATED',
  REFUSED: 'REFUSED',
  IN_PROGRESS: 'IN_PROGRESS',
  WITHDRAWN: 'WITHDRAWN',
  DELETED: 'DELETED',
};

export const YOUNG_STATUS_PHASE1 = {
  WAITING_AFFECTATION: 'WAITING_AFFECTATION',
  AFFECTED: 'AFFECTED',
  CANCEL: 'CANCEL',
  DONE: 'DONE',
  NOT_DONE: 'NOT_DONE',
};

export const YOUNG_STATUS_PHASE2 = {
  WAITING_REALISATION: 'WAITING_REALISATION',
  IN_PROGRESS: 'IN_PROGRESS',
  VALIDATED: 'VALIDATED',
};

export const YOUNG_STATUS_PHASE3 = {
  WAITING_REALISATION: 'WAITING_REALISATION',
  WAITING_VALIDATION: 'WAITING_VALIDATION',
  VALIDATED: 'VALIDATED',
};

export const YOUNG_PHASE = {
  INSCRIPTION: 'INSCRIPTION',
  COHESION_STAY: 'COHESION_STAY',
  INTEREST_MISSION: 'INTEREST_MISSION',
  CONTINUE: 'CONTINUE',
};

export const PHASE_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  IN_COMING: 'IN_COMING',
  VALIDATED: 'VALIDATED',
  CANCEL: 'CANCEL',
  WAITING_AFFECTATION: 'WAITING_AFFECTATION',
};

export const APPLICATION_STATUS = {
  WAITING_VALIDATION: 'WAITING_VALIDATION',
  WAITING_ACCEPTATION: 'WAITING_ACCEPTATION',
  VALIDATED: 'VALIDATED',
  REFUSED: 'REFUSED',
  CANCEL: 'CANCEL',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  ABANDON: 'ABANDON',
};

export const PROFESSIONNAL_PROJECT = {
  UNIFORM: 'UNIFORM',
  OTHER: 'OTHER',
  UNKNOWN: 'UNKNOWN',
};

export const PROFESSIONNAL_PROJECT_PRECISION = {
  FIREFIGHTER: 'FIREFIGHTER',
  POLICE: 'POLICE',
  ARMY: 'ARMY',
};

export const MISSION_DOMAINS = {
  CITIZENSHIP: 'CITIZENSHIP',
  CULTURE: 'CULTURE',
  DEFENSE: 'DEFENSE',
  EDUCATION: 'EDUCATION',
  ENVIRONMENT: 'ENVIRONMENT',
  HEALTH: 'HEALTH',
  SECURITY: 'SECURITY',
  SOLIDARITY: 'SOLIDARITY',
  SPORT: 'SPORT',
};

export const YOUNG_SITUATIONS = {
  GENERAL_SCHOOL: 'GENERAL_SCHOOL',
  PROFESSIONAL_SCHOOL: 'PROFESSIONAL_SCHOOL',
  AGRICULTURAL_SCHOOL: 'AGRICULTURAL_SCHOOL',
  SPECIALIZED_SCHOOL: 'SPECIALIZED_SCHOOL',
  APPRENTICESHIP: 'APPRENTICESHIP',
  EMPLOYEE: 'EMPLOYEE',
  INDEPENDANT: 'INDEPENDANT',
  SELF_EMPLOYED: 'SELF_EMPLOYED',
  ADAPTED_COMPANY: 'ADAPTED_COMPANY',
  POLE_EMPLOI: 'POLE_EMPLOI',
  MISSION_LOCALE: 'MISSION_LOCALE',
  CAP_EMPLOI: 'CAP_EMPLOI',
  NOTHING: 'NOTHING', // @todo find a better key --'
};

export const FORMAT = {
  CONTINUOUS: 'CONTINUOUS',
  DISCONTINUOUS: 'DISCONTINUOUS',
  AUTONOMOUS: 'AUTONOMOUS',
};

export const REFERENT_ROLES = {
  ADMIN: 'admin',
  REFERENT_DEPARTMENT: 'referent_department',
  REFERENT_REGION: 'referent_region',
  RESPONSIBLE: 'responsible',
  SUPERVISOR: 'supervisor',
};

export const REFERENT_DEPARTMENT_SUBROLE = {
  manager_department: 'manager_department',
  assistant_manager_department: 'assistant_manager_department',
  manager_department_phase2: 'manager_department_phase2',
  secretariat: 'secretariat',
};
export const REFERENT_REGION_SUBROLE = {
  coordinator: 'coordinator',
  assistant_coordinator: 'assistant_coordinator',
};

export const MISSION_STATUS = {
  WAITING_VALIDATION: 'WAITING_VALIDATION',
  WAITING_CORRECTION: 'WAITING_CORRECTION',
  VALIDATED: 'VALIDATED',
  DRAFT: 'DRAFT',
  REFUSED: 'REFUSED',
  CANCEL: 'CANCEL',
  ARCHIVED: 'ARCHIVED',
};

export const PERIOD = {
  DURING_HOLIDAYS: 'DURING_HOLIDAYS',
  DURING_SCHOOL: 'DURING_SCHOOL',
};

export const TRANSPORT = {
  PUBLIC_TRANSPORT: 'PUBLIC_TRANSPORT',
  BIKE: 'BIKE',
  MOTOR: 'MOTOR',
  CARPOOLING: 'CARPOOLING',
  OTHER: 'OTHER',
};

export const MISSION_PERIOD_DURING_HOLIDAYS = {
  SUMMER: 'SUMMER',
  AUTUMN: 'AUTUMN',
  DECEMBER: 'DECEMBER',
  WINTER: 'WINTER',
  SPRING: 'SPRING',
};

export const MISSION_PERIOD_DURING_SCHOOL = {
  EVENING: 'EVENING',
  END_DAY: 'END_DAY',
  WEEKEND: 'WEEKEND',
};

export const STRUCTURE_STATUS = {
  WAITING_VALIDATION: 'WAITING_VALIDATION',
  WAITING_CORRECTION: 'WAITING_CORRECTION',
  VALIDATED: 'VALIDATED',
  DRAFT: 'DRAFT',
};

export const DEFAULT_STRUCTURE_NAME = 'Ma nouvelle Structure';

export const COHESION_STAY_LIMIT_DATE = {
  2019: 'du 16 au 28 juin 2019',
  2020: 'Du 21 juin au 2 juillet 2021',
  2021: 'Du 21 juin au 2 juillet 2021',
};

export const INTEREST_MISSION_LIMIT_DATE = {
  2019: '23 mars 2021',
  2020: '31 décembre 2021',
  2021: '30 juin 2022',
};
