export const uselessSettings = {
  toolkit: "",
  zones: "",
  eligibility: "",
  isAssignmentAnnouncementsOpenForYoungFrom: "",
  isAssignmentAnnouncementsOpenForYoungTo: "",
  manualAffectionOpenForAdminFrom: "",
  manualAffectionOpenForAdminTo: "",
  manualAffectionOpenForReferentRegionFrom: "",
  manualAffectionOpenForReferentRegionTo: "",
  manualAffectionOpenForReferentDepartmentFrom: "",
  manualAffectionOpenForReferentDepartmentTo: "",
  youngCheckinForAdminFrom: "",
  youngCheckinForAdminTo: "",
  youngCheckinForHeadOfCenterFrom: "",
  youngCheckinForHeadOfCenterTo: "",
  youngCheckinForRegionReferentFrom: "",
  youngCheckinForRegionReferentTo: "",
  youngCheckinForDepartmentReferentFrom: "",
  youngCheckinForDepartmentReferentTo: "",
  busListAvailabilityFrom: "",
  busListAvailabilityTo: "",
  repartitionSchemaCreateGroupAvailabilityFrom: "",
  repartitionSchemaCreateGroupAvailabilityTo: "",
  repartitionSchemaDownloadAvailabilityFrom: "",
  repartitionSchemaDownloadAvailabilityTo: "",
};

export const settings = {
  name: "",
  snuId: "",
  dateStart: "",
  dateEnd: "",
  pdrChoiceLimitDate: "",
  validationDate: "",
  validationDateForTerminaleGrade: "",
  manualAffectionOpenForAdmin: false,
  manualAffectionOpenForReferentRegion: false,
  manualAffectionOpenForReferentDepartment: false,
  isAssignmentAnnouncementsOpenForYoung: false,
  youngCheckinForAdmin: false,
  youngCheckinForHeadOfCenter: false,
  youngCheckinForRegionReferent: false,
  youngCheckinForDepartmentReferent: false,
  busListAvailability: false,
  repartitionSchemaCreateGroupAvailability: false,
  repartitionSchemaDownloadAvailability: false,
};
