import { MONGO_COLLECTION } from "../../mongoSchema";

export enum PERMISSION_RESOURCES_SCRIPT {
  EXPORT_INJEP = "EXPORT_INJEP",
  EXPORT_DSNJ = "EXPORT_DSNJ",
  AFFECTER_HTS = "AFFECTER_HTS",
  DASHBOARD = "DASHBOARD",
  SETTINGS = "SETTINGS",
}

export enum PERMISSION_RESOURCES_PROVIDER {
  SUPPORT = "SUPPORT",
  ASSOCIATION = "ASSOCIATION", // API ENGAGEMENT
}

export const PERMISSION_RESOURCES = {
  ...MONGO_COLLECTION,
  ...PERMISSION_RESOURCES_SCRIPT,
  ...PERMISSION_RESOURCES_PROVIDER,
} as const;

export const PERMISSION_RESOURCES_LIST = Object.values(PERMISSION_RESOURCES);
