import { MONGO_COLLECTION } from "../../mongoSchema";

export enum PERMISSION_RESOURCES_SCRIPT {
  ACCUEIL = "ACCUEIL",
  AFFECTER_HTS = "AFFECTER_HTS",
  DASHBOARD = "DASHBOARD",
  EXPORT_DSNJ = "EXPORT_DSNJ",
  EXPORT_INJEP = "EXPORT_INJEP",
  IMPORT_SI_SNU = "IMPORT_SI_SNU",
  SETTINGS = "SETTINGS",
  USER_HISTORY = "USER_HISTORY",
  USER_NOTIFICATIONS = "USER_NOTIFICATIONS",
}

export enum PERMISSION_RESOURCES_PROVIDER {
  SUPPORT = "SUPPORT",
  ASSOCIATION = "ASSOCIATION", // API ENGAGEMENT
}

export const PERMISSION_RESOURCES = {
  ...MONGO_COLLECTION,
  ...PERMISSION_RESOURCES_SCRIPT,
  ...PERMISSION_RESOURCES_PROVIDER,
} as const;

export const PERMISSION_RESOURCES_LIST = Object.values(PERMISSION_RESOURCES);
