name: "Get an unique image tag"
description: "Get an unique image tag based on date and current commit"

outputs:
  image_tag:
    description: "Image Tag"
    value: ${{ steps.image_tag.outputs.image_tag }}

runs:
  using: "composite"
  steps:
    - name: Get commit hash
      id: commit
      uses: prompt/actions-commit-hash@v3

    - name: Get current date
      id: date
      shell: bash
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Get image tag
      id: image_tag
      shell: bash
      run: |
        image_tag="${{ steps.date.outputs.date }}-${{ steps.commit.outputs.short }}"
        echo $image_tag
        echo "image_tag=$image_tag" >> $GITHUB_OUTPUT
