name: "Get an unique image tag"
description: "Get an unique image tag based on date and current commit"

inputs:
  sha:
    description: "The sha of the commit"
    required: true

outputs:
  image_tag:
    description: "Image Tag"
    value: ${{ steps.image_tag.outputs.image_tag }}

runs:
  using: "composite"
  steps:
    - name: Get commit hash
      id: commit
      shell: bash
      run: |
        sha=$(cut -c"1-8" <<< ${{ inputs.sha }})
        echo "sha=$sha" >> $GITHUB_OUTPUT

    - name: Get image tag
      id: image_tag
      shell: bash
      run: |
        image_tag="${{ steps.commit.outputs.sha }}"
        echo $image_tag
        echo "image_tag=$image_tag" >> $GITHUB_OUTPUT
