name: Libraries - Run Tests

inputs:
  branch_name:
    description: "Branch name"
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-workspace
      with:
        branch_name: ${{ inputs.branch_name }}
        build: lib

    - name: Lint lib code
      working-directory: packages/lib
      shell: bash
      run: npm run lint

    - name: Test lib
      working-directory: packages/lib
      shell: bash
      run: npm run test

    - name: Build ds
      working-directory: packages/ds
      shell: bash
      run: npm run build

    - name: Lint ds code
      working-directory: packages/ds
      shell: bash
      run: npm run lint
