name: Front applications - Run Tests

inputs:
  branch_name:
    description: "Branch name"
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-workspace
      with:
        branch_name: ${{ inputs.branch_name }}
        build: lib ds

    - name: Check types
      working-directory: admin
      shell: bash
      run: npm run check-types

    - name: Lint code
      working-directory: admin
      shell: bash
      run: npm run lint
