const tickets = [
  {
    id: 19,
    group_id: 1,
    priority_id: 2,
    state_id: 1,
    organization_id: null,
    number: "45019",
    title: "Test Ursule",
    owner_id: 1,
    customer_id: 13,
    note: null,
    first_response_at: null,
    first_response_escalation_at: null,
    first_response_in_min: null,
    first_response_diff_in_min: null,
    close_at: null,
    close_escalation_at: null,
    close_in_min: null,
    close_diff_in_min: null,
    update_escalation_at: null,
    update_in_min: null,
    update_diff_in_min: null,
    last_contact_at: "2021-08-31T14:00:17.712Z",
    last_contact_agent_at: null,
    last_contact_customer_at: "2021-08-31T14:00:17.712Z",
    last_owner_update_at: null,
    create_article_type_id: 11,
    create_article_sender_id: 2,
    article_count: 7,
    escalation_at: null,
    pending_time: null,
    type: null,
    time_unit: null,
    preferences: {},
    updated_by_id: 13,
    created_by_id: 13,
    created_at: "2021-08-31T14:00:17.639Z",
    updated_at: "2021-08-31T14:04:02.344Z",
  },
  {
    id: 20,
    group_id: 1,
    priority_id: 2,
    state_id: 4,
    organization_id: null,
    number: "45020",
    title: "test 2 ursule",
    owner_id: 1,
    customer_id: 13,
    note: null,
    first_response_at: null,
    first_response_escalation_at: null,
    first_response_in_min: null,
    first_response_diff_in_min: null,
    close_at: "2021-08-31T14:04:44.094Z",
    close_escalation_at: null,
    close_in_min: null,
    close_diff_in_min: null,
    update_escalation_at: null,
    update_in_min: null,
    update_diff_in_min: null,
    last_contact_at: "2021-08-31T14:04:44.166Z",
    last_contact_agent_at: null,
    last_contact_customer_at: "2021-08-31T14:04:44.166Z",
    last_owner_update_at: null,
    create_article_type_id: 11,
    create_article_sender_id: 2,
    article_count: 1,
    escalation_at: null,
    pending_time: null,
    type: null,
    time_unit: null,
    preferences: {},
    updated_by_id: 13,
    created_by_id: 13,
    created_at: "2021-08-31T14:04:44.091Z",
    updated_at: "2021-08-31T14:04:44.188Z",
  },
  {
    id: 21,
    group_id: 1,
    priority_id: 2,
    state_id: 2,
    organization_id: null,
    number: "45021",
    title: "Je n'arrive pas à téléverser mes justificatifs de PM",
    owner_id: 5,
    customer_id: 17,
    note: null,
    first_response_at: null,
    first_response_escalation_at: null,
    first_response_in_min: null,
    first_response_diff_in_min: null,
    close_at: null,
    close_escalation_at: null,
    close_in_min: null,
    close_diff_in_min: null,
    update_escalation_at: null,
    update_in_min: null,
    update_diff_in_min: null,
    last_contact_at: "2021-09-02T09:30:12.085Z",
    last_contact_agent_at: null,
    last_contact_customer_at: "2021-09-02T09:30:12.085Z",
    last_owner_update_at: null,
    create_article_type_id: 5,
    create_article_sender_id: 2,
    article_count: 1,
    escalation_at: null,
    pending_time: null,
    type: null,
    time_unit: null,
    preferences: {},
    updated_by_id: 5,
    created_by_id: 5,
    created_at: "2021-09-02T09:30:11.959Z",
    updated_at: "2021-09-03T05:31:55.813Z",
  },
  {
    id: 22,
    group_id: 1,
    priority_id: 2,
    state_id: 2,
    organization_id: null,
    number: "45022",
    title: "Test ticket téléversement",
    owner_id: 1,
    customer_id: 13,
    note: null,
    first_response_at: null,
    first_response_escalation_at: null,
    first_response_in_min: null,
    first_response_diff_in_min: null,
    close_at: null,
    close_escalation_at: null,
    close_in_min: null,
    close_diff_in_min: null,
    update_escalation_at: null,
    update_in_min: null,
    update_diff_in_min: null,
    last_contact_at: "2021-09-02T09:54:56.094Z",
    last_contact_agent_at: null,
    last_contact_customer_at: "2021-09-02T09:54:56.094Z",
    last_owner_update_at: null,
    create_article_type_id: 5,
    create_article_sender_id: 2,
    article_count: 2,
    escalation_at: null,
    pending_time: null,
    type: null,
    time_unit: null,
    preferences: {},
    updated_by_id: 3,
    created_by_id: 5,
    created_at: "2021-09-02T09:54:56.000Z",
    updated_at: "2021-09-20T08:35:11.746Z",
  },
  {
    id: 23,
    group_id: 1,
    priority_id: 3,
    state_id: 4,
    organization_id: null,
    number: "45023",
    title: "Ticket autre fermé",
    owner_id: 5,
    customer_id: 13,
    note: null,
    first_response_at: null,
    first_response_escalation_at: null,
    first_response_in_min: null,
    first_response_diff_in_min: null,
    close_at: "2021-09-03T06:59:36.513Z",
    close_escalation_at: null,
    close_in_min: null,
    close_diff_in_min: null,
    update_escalation_at: null,
    update_in_min: null,
    update_diff_in_min: null,
    last_contact_at: "2021-09-03T05:46:29.154Z",
    last_contact_agent_at: null,
    last_contact_customer_at: "2021-09-03T05:46:29.154Z",
    last_owner_update_at: null,
    create_article_type_id: 5,
    create_article_sender_id: 2,
    article_count: 1,
    escalation_at: null,
    pending_time: null,
    type: null,
    time_unit: null,
    preferences: {
      escalation_calculation: {
        escalation_disabled: true,
      },
    },
    updated_by_id: 5,
    created_by_id: 5,
    created_at: "2021-09-03T05:46:29.012Z",
    updated_at: "2021-09-03T06:59:36.510Z",
  },
  {
    id: 24,
    group_id: 1,
    priority_id: 2,
    state_id: 4,
    organization_id: null,
    number: "45024",
    title: "test autre ticket test fermé",
    owner_id: 5,
    customer_id: 13,
    note: null,
    first_response_at: null,
    first_response_escalation_at: null,
    first_response_in_min: null,
    first_response_diff_in_min: null,
    close_at: "2021-09-03T05:47:13.879Z",
    close_escalation_at: null,
    close_in_min: null,
    close_diff_in_min: null,
    update_escalation_at: null,
    update_in_min: null,
    update_diff_in_min: null,
    last_contact_at: "2021-09-03T05:47:13.978Z",
    last_contact_agent_at: null,
    last_contact_customer_at: "2021-09-03T05:47:13.978Z",
    last_owner_update_at: null,
    create_article_type_id: 5,
    create_article_sender_id: 2,
    article_count: 1,
    escalation_at: null,
    pending_time: null,
    type: null,
    time_unit: null,
    preferences: {},
    updated_by_id: 5,
    created_by_id: 5,
    created_at: "2021-09-03T05:47:13.876Z",
    updated_at: "2021-09-03T05:47:14.000Z",
  },
];

export default tickets;
