import { YOUNG_SOURCE } from "snu-lib";
interface File {
    name?: string;
    uploadedAt?: Date;
    size?: number;
    mimetype?: string;
    category?: string;
    expirationDate?: Date;
    side?: string;
}

interface CorrectionRequest {
    moderatorId?: string;
    cohort?: string;
    field?: string;
    reason?: string;
    message?: string;
    status?: string;
    createdAt?: Date;
    sentAt?: Date;
    remindedAt?: Date;
    correctedAt?: Date;
    canceledAt?: Date;
}
interface Referent {
    id?: string;
    firstName?: string;
    lastName?: string;
    role?: string;
}

export type NoteType = {
    phase?: string;
    note?: string;
    referent?: Referent;
    createdAt?: Date;
    updatedAt?: Date;
};

export type JeuneModel = {
    id: string;
    phase?: string;
    prenom?: string;
    nom?: string;
    statut: string;
    email: string;
    source: keyof typeof YOUNG_SOURCE;
    telephone?: string;
    nationaliteFR?: string;
    paysNaissance?: string;
    villeNaissance?: string;
    codePostalVilleNaissance?: string;
    emailVerifie?: string;
    nouvelEmail?: string;
    zoneTelephone?: string;
    dateNaissance?: Date;
    handicapMemeDepartement?: string;
    genre?: string;
    qpv?: string;
    psh?: string;
    departement?: string;
    region?: string;
    departementScolarite?: string;
    regionScolarite?: string;
    paysScolarite?: string;
    localisation?: {
        lat?: number;
        lon?: number;
    };
    dernierStatutLe?: Date;
    raisonDesistement?: string;
    messageDesistement?: string;
    aCommenceReinscription?: string;
    etapeReinscription2023?: string;
    etapeInscription2023?: string;
    etapeInscription?: string;
    dateInscriptionFinalisee?: Date;
    etapeCohesion2020?: string;
    messageCorrectionInscription?: string;
    messageRefusInscription?: string;
    adresse?: string;
    niveauPrecisionCoordonnees?: string;
    complementAdresse?: string;
    codePostal?: string;
    ville?: string;
    adresseVerifiee?: string;
    codeVille?: string;
    densitePopulation?: string;
    estRegionRurale?: string;
    pays?: string;
    adresseEtranger?: string;
    villeEtranger?: string;
    codePostalEtranger?: string;
    paysEtranger?: string;
    situation?: string;
    niveauEtudes?: string;
    certificationScolaire?: string;
    scolarise?: string;
    employe?: string;
    sessionId?: string;
    sessionNom?: string;
    originalSessionId?: string;
    originalSessionNom?: string;
    sessionChangeReasonDetail?: string;
    sessionChangeReason?: string;
    nomHote?: string;
    prenomHote?: string;
    relationHote?: string;
    villeHote?: string;
    codePostalHote?: string;
    adresseHote?: string;
    departementHote?: string;
    regionHote?: string;
    handicap?: string;
    allergies?: string;
    handicapDansMemeDepartement?: string;
    accesMobiliteReduite?: string;
    beneficiairePPS?: string;
    beneficiairePAI?: string;
    structureEngagee?: string;
    memeEcoleCLE?: string;
    amenagementSpecifique?: string;
    typeAmenagementSpecifique?: string;
    activiteHautNiveau?: string;
    activiteHautNiveauDansMemeDepartement?: string;
    typeActiviteHautNiveau?: string;
    autorisationSNU?: string;
    autorisationSNUParent1?: string;
    autorisationSNUParent2?: string;
    dateValidationParent1?: Date;
    dateValidationParent2?: Date;
    fichiersConsentementTraitementDonnees?: string[];
    consentementParent?: string;
    fichiersConsentementParent?: string[];
    fichiersConsentementParentConformes?: string;
    informationsFichiersConsentementParent?: string;
    consentement?: string;
    droitImage?: string;
    fichiersDroitImage?: string[];
    statutFichiersDroitImage?: string;
    commentaireFichiersDroitImage?: string;
    autotestPCR?: string;
    fichiersAutotestPCR?: string[];
    statutFichiersAutotestPCR?: string;
    commentaireFichiersAutotestPCR?: string;
    reglementJeune?: string;
    reglementParent1?: string;
    reglementParent2?: string;
    fichiersReglement?: string[];
    exactitudeInformations?: string;
    acquittementDisponibiliteSessionTerminale?: string;
    attestationSurLhonneurParentIdInvalide?: string;
    journeeDefenseCitoyennete?: string;
    motivations?: string;
    domaines?: string[];
    projetProfessionnel?: string;
    precisionProjetProfessionnel?: string;
    periode?: string;
    classementPeriode?: string[];
    mobiliteProcheEcole?: string;
    mobiliteProcheDomicile?: string;
    mobiliteProcheProche?: string;
    nomProcheMobilite?: string;
    adresseProcheMobilite?: string;
    codePostalProcheMobilite?: string;
    villeProcheMobilite?: string;
    transportsMobilite?: string[];
    autresTransportsMobilite?: string;
    formatMission?: string;
    engagement?: string;
    cniFiles?: string[];
    fichiers?: {
        cniFiles?: File[];
        highSkilledActivityProofFiles?: File[];
        dataProcessingConsentmentFiles?: File[];
        parentConsentmentFiles?: File[];
        imageRightFiles?: File[];
        autoTestPCRFiles?: File[];
        rulesFiles?: File[];
        militaryPreparationFilesIdentity?: File[];
        militaryPreparationFilesCensus?: File[];
        militaryPreparationFilesAuthorization?: File[];
        militaryPreparationFilesCertificate?: File[];
    };
    descriptionEngagement?: string;
    localisationDesiree?: string;
    fichiersPreparationMilitaireIdentite?: string[];
    fichiersPreparationMilitaireRecensement?: string[];
    fichiersPreparationMilitaireAutorisation?: string[];
    fichiersPreparationMilitaireCertificat?: string[];
    statutFichiersPreparationMilitaire?: string;
    messageCorrectionPreparationMilitaire?: string;
    dateExpirationDernierFichierCNI?: Date;
    fichierCNINonValideAuDebut?: string;
    categorieDernierFichierCNI?: string;
    missionsInMail?: { missionId?: string; date?: Date }[];
    status_equivalence?: string;
    correctionRequests?: CorrectionRequest[];
    notes?: NoteType[];
    hasNotes?: string;
    defenseInterest?: string;
    defenseTypeInterest?: string;
    defenseDomainInterest?: string;
    defenseMotivationInterest?: string;
    securityInterest?: string;
    securityDomainInterest?: string;
    solidarityInterest?: string;
    healthInterest?: string;
    educationInterest?: string;
    cultureInterest?: string;
    sportInterest?: string;
    environmentInterest?: string;
    citizenshipInterest?: string;
    deletedAt?: Date;
    createdAt?: Date;
    updatedAt?: Date;

    // school Info
    nomEtablissement?: string;
    ancienNomEtablissement?: string;
    typeEtablissement?: string;
    adresseEtablissement?: string;
    complementAdresseEtablissement?: string;
    codePostalEtablissement?: string;
    villeEtablissement?: string;
    departementEtablissement?: string;
    regionEtablissement?: string;
    paysEtablissement?: string;
    ecoleRamsesId?: string;
    academie?: string;
    classeId?: string;
    etablissementId?: string;
    localisationEtablissement?: { lat?: number; lon?: number };

    // transport info
    transportInfoGivenByLocal?: string;
    hasMeetingInformation?: string;
    isTravelingByPlane?: string;
    deplacementPhase1Autonomous?: string;
    busTmp?: string;
    pointDeRassemblementId?: string;
    ligneDeBusId?: string;
    hasPDR?: string;

    // Phase1 info
    statutPhase1: string;
    expirationAutoAffectationPhase1?: Date;
    statutPhase1Tmp?: string;
    statutPhase1Motif?: string;
    statutPhase1MotifDetail?: string;
    codeCenterTmp?: string;
    nomCentreCohesion?: string;
    codePostalCentreCohesion?: string;
    villeCentreCohesion?: string;
    centreId?: string;
    sejourId?: string;
    sejourIdTemp?: string;
    cohesionStayPresence?: string;
    presenceJDM?: string;
    departInform?: string;
    departSejourAt?: string;
    departSejourMotif?: string;
    departSejourMotifComment?: string;
    youngPhase1Agreement: string;
    cohesionStayMedicalFileReceived?: string;

    // Parent 1 Information
    parent1Prenom?: string;
    parent1Nom?: string;
    parent1Email?: string;
    parent1Telephone?: string;
    parent1Location?: { lat?: number; lon?: number };
    statutParent1?: string;
    prenomParent1?: string;
    nomParent1?: string;
    emailParent1?: string;
    telephoneParent1?: string;
    zoneTelephoneParent1?: string;
    aUneAdressePropreParent1?: string;
    adresseParent1?: string;
    niveauPrecisionCoordonneesParent1?: string;
    complementAdresseParent1?: string;
    codePostalParent1?: string;
    villeParent1?: string;
    codeVilleParent1?: string;
    departementParent1?: string;
    regionParent1?: string;
    paysParent1?: string;
    provenanceFranceConnectParent1?: string;
    tokenInscription2023Parent1?: string;
    donneesVerifieesParent1?: string;
    adresseVerifieeParent1?: string;
    autorisationAutotestCovidParent1?: string;
    autorisationDroitImageParent1?: string;
    preferenceContactParent1?: string;

    // Parent 2 Information
    parent2Prenom?: string;
    parent2Nom?: string;
    parent2Email?: string;
    parent2Telephone?: string;
    parent2Location?: { lat?: number; lon?: number };
    statutParent2?: string;
    prenomParent2?: string;
    nomParent2?: string;
    emailParent2?: string;
    telephoneParent2?: string;
    zoneTelephoneParent2?: string;
    aUneAdressePropreParent2?: string;
    adresseParent2?: string;
    niveauPrecisionCoordonneesParent2?: string;
    complementAdresseParent2?: string;
    codePostalParent2?: string;
    villeParent2?: string;
    codeVilleParent2?: string;
    departementParent2?: string;
    regionParent2?: string;
    paysParent2?: string;
    localisationParent2?: { lat?: number; lon?: number };
    provenanceFranceConnectParent2?: string;
    tokenInscription2023Parent2?: string;
    autorisationDroitImageParent2?: string;
    reinitialisationAutorisationDroitImageParent?: string;
    preferenceContactParent2?: string;

    //phase2 info
    statutCandidaturePhase2?: string[];
    typeFichiersCandidaturePhase2?: string[];
    nombreHeuresEffectueesPhase2?: string;
    nombreHeuresEstimeesPhase2?: string;
    statutPhase2?: string;
    statutPhase2UpdatedAt?: Date;
    statutPhase2OpenedAt?: Date;
    statutPhase2Valide?: Date;
    statutPhase2Contrat?: string[];

    structureMedicoSociale?: string;
    nomStructureMedicosociale?: string;
    adresseStructureMedicosociale?: string;
    complementAdresseStructureMedicosociale?: string;
    codePostalStructureMedicosociale?: string;
    villeStructureMedicosociale?: string;
    departementStructureMedicosociale?: string;
    regionStructureMedicosociale?: string;
    medicosocialStructureLocation?: {
        lat?: number;
        lon?: number;
    };

    //phase3 info LEGACY
    statutPhase3?: string;
    statutPhase3UpdatedAt?: Date;
    statutPhase3Valide?: Date;
    nomStructurePhase3?: string;
    domaineMissionPhase3?: string;
    descriptionMissionPhase3?: string;
    dateDebutMissionPhase3?: Date;
    dateFinMissionPhase3?: Date;
    prenomTuteurPhase3?: string;
    nomTuteurPhase3?: string;
    emailTuteurPhase3?: string;
    telephoneTuteurPhase3?: string;
    noteTuteurPhase3?: string;
    tokenPhase3?: string;
};

export type CreateJeuneModel = Omit<JeuneModel, "id" | "createdAt" | "updatedAt">;
