services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/mongodb
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/data/elastic
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - redis
  redis-ui:
    image: redis/redisinsight
    container_name: redis-ui
    ports:
      - "5540:5540"
    networks:
      - redis
  bullboard:
    container_name: bullboard
    image: venatum/bull-board:1.5
    restart: always
    ports:
      - 3001:3000
    environment:
      - REDIS_HOST=redis
    networks:
      - redis

networks:
  redis:
    driver: bridge

volumes:
  mongodb_data:
  elasticsearch_data:
