FROM mongo:7

RUN cat /etc/apt/sources.list
RUN rm /etc/apt/sources.list

# curl updates
RUN echo "deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted" >> /etc/apt/sources.list

RUN apt-get update
RUN apt-get -y install curl

COPY ./local/env_setup.sh .
COPY ./elastic-search ./elastic-search/

ENV MONGO_LOCAL_URL=
ENV DUMP_DIRECTORY=
ENV ES_ENDPOINT=

CMD ["./env_setup.sh"]
