export const ACTIONS = {
  TRANSPORT: {
    UPDATE: "TRANSPORT:UPDATE",
    UPDATE_PDR_ID: "TRANSPORT:UPDATE_PDR_ID",
    UPDATE_PDR_SCHEDULE: "TRANSPORT:UPDATE_PDR_SCHEDULE",
    UPDATE_TYPE: "TRANSPORT:UPDATE_TYPE",
    UPDATE_SESSION_ID: "TRANSPORT:UPDATE_SESSION_ID",
    UPDATE_CENTER_SCHEDULE: "TRANSPORT:UPDATE_CENTER_SCHEDULE",
    SEND_NOTIFICATION: "TRANSPORT:SEND_NOTIFICATION",
  },
  PHASE_1: {
    POINTAGE: "PHASE_1:POINTAGE",
  },
  CONTRACT: {
    CREATE: "CONTRACT:CREATE",
    UPDATE: "CONTRACT:UPDATE",
  },
};
