export const ACTIONS = {
  TRANSPORT: {
    UPDATE: "TRANSPORT:UPDATE",
    UPDATE_PDR_ID: "TRANSPORT:UPDATE_PDR_ID",
    UPDATE_PDR_SCHEDULE: "TRANSPORT:UPDATE_PDR_SCHEDULE",
    UPDATE_TYPE: "TRANSPORT:UPDATE_TYPE",
    UPDATE_SESSION_ID: "TRANSPORT:UPDATE_SESSION_ID",
    UPDATE_CENTER_SCHEDULE: "TRANSPORT:UPDATE_CENTER_SCHEDULE",
    PREVIEW_NOTIFICATION: "TRANSPORT:PREVIEW_NOTIFICATION",
    NOTIFY_AFTER_UPDATE: "TRANSPORT:NOTIFY_AFTER_UPDATE",
  },
};
