import { CORRECTION_STEPS } from "../../utils/navigation";

export const CORRECTION_MAP_HTS = {
  [CORRECTION_STEPS.PROFIL]: {
    fields: ["firstName", "lastName", "phone", "email"],
    url: "/inscription/correction/profil",
  },
  [CORRECTION_STEPS.ELIGIBILITE]: {
    fields: [
      "birthdateAt",
      "schooled",
      "grade",
      "schoolName",
      "schoolType",
      "schoolAddress",
      "schoolZip",
      "schoolCity",
      "schoolDepartment",
      "schoolRegion",
      "schoolCountry",
      "schoolId",
      "zip",
    ],
    url: "/inscription/correction/eligibilite",
  },
  [CORRECTION_STEPS.REPRESENTANTS]: {
    fields: [
      "parent1Status",
      "parent1FirstName",
      "parent1LastName",
      "parent1Email",
      "parent1Phone",
      "parent2",
      "parent2Status",
      "parent2FirstName",
      "parent2LastName",
      "parent2Email",
      "parent2Phone",
    ],
    url: "/inscription/correction/representants",
  },
  [CORRECTION_STEPS.COORDONNEES]: {
    fields: [
      "gender",
      "frenchNationality",
      "birthCountry",
      "birthCity",
      "birthCityZip",
      "situation",
      "livesInFrance",
      "addressVerified",
      "country",
      "city",
      "zip",
      "address",
      "location",
      "department",
      "region",
      "cityCode",
      "foreignCountry",
      "foreignCity",
      "foreignZip",
      "foreignAddress",
      "hostLastName",
      "hostFirstName",
      "hostRelationship",
      "handicap",
      "ppsBeneficiary",
      "paiBeneficiary",
      "allergies",
      "moreInformation",
      "specificAmenagment",
      "specificAmenagmentType",
      "reducedMobilityAccess",
      "handicapInSameDepartment",
      "psc1Info",
    ],
    url: "/inscription/correction/coordonnee",
  },
  [CORRECTION_STEPS.DOCUMENTS]: {
    fields: ["cniFile", "latestCNIFileExpirationDate", "latestCNIFileCategory"],
    url: "/inscription/correction/documents",
  },
};

export const CORRECTION_MAP_CLE = {
  [CORRECTION_STEPS.PROFIL]: {
    fields: ["firstName", "lastName", "frenchNationality", "phone", "email", "birthdateAt", "grade"],
    url: "/inscription/correction/profil",
  },
  [CORRECTION_STEPS.REPRESENTANTS]: {
    fields: [
      "parent1Status",
      "parent1FirstName",
      "parent1LastName",
      "parent1Email",
      "parent1Phone",
      "parent2",
      "parent2Status",
      "parent2FirstName",
      "parent2LastName",
      "parent2Email",
      "parent2Phone",
    ],
    url: "/inscription/correction/representants",
  },
  [CORRECTION_STEPS.COORDONNEES]: {
    fields: [
      "gender",
      "birthCountry",
      "birthCity",
      "birthCityZip",
      "situation",
      "livesInFrance",
      "addressVerified",
      "country",
      "city",
      "zip",
      "address",
      "location",
      "department",
      "region",
      "cityCode",
      "foreignCountry",
      "foreignCity",
      "foreignZip",
      "foreignAddress",
      "hostLastName",
      "hostFirstName",
      "hostRelationship",
      "handicap",
      "ppsBeneficiary",
      "paiBeneficiary",
      "allergies",
      "moreInformation",
      "specificAmenagment",
      "specificAmenagmentType",
      "reducedMobilityAccess",
      "handicapInSameDepartment",
      "psc1Info",
    ],
    url: "/inscription/correction/coordonnee",
  },
};
