name: "Docker Build & Publish"
description: "Build & Publish a Docker image to a Container Registry"

inputs:
  username:
    description: "Username for Docker registry"
    required: true
  password:
    description: "Password for Docker registry"
    required: true
  registry:
    description: "Registry endpoint"
    required: true
  image_name:
    description: "Name of the image"
    required: true
  image_tag:
    description: "Unique tag of the image"
    required: true
  image_tag_stable:
    description: "Stable tag for the image"
    required: false
    default: "latest"
  dockerfile_path:
    description: "Path to the application's Dockerfile"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        registry: ${{ inputs.registry }}

    - name: Get current date
      id: date
      shell: bash
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      shell: bash
      run: |
        docker build \
          -t ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }} \
          -t ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag_stable }} \
          --label "created_at=${{ steps.date.outputs.date }}" \
          -f ${{ inputs.dockerfile_path }} .

    - name: Push the Docker Image
      shell: bash
      run: |
        docker push ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
        docker push ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag_stable }}
