name: ADMIN - Build Docker image & Deploy Scaleway

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - admin/**
#       - packages/**

on:
  push:
    branches:
      - feat-1469

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Node 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Lint code
        working-directory: ${{ env.SUBFOLDER_NAME }}
        continue-on-error: true
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      ACTIVE_HOSTING: ${{ secrets.ACTIVE_HOSTING }}

    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create SSH key
        uses: ./.github/actions/ssh-key
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Remove git folder
        run: rm -rf .git

      - name: Docker Build & Publish
        uses: ./.github/actions/docker
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
          # registry: ${{ secrets.SCW_CONTAINER_REGISTRY_ENDPOINT }}
          registry: rg.fr-par.scw.cloud/funcscwsnutestvfku19oc
          image_name: admin
          dockerfile_path: admin/Dockerfile

      - name: Scaleway container deploy
        if: env.ACTIVE_HOSTING == 'scaleway'
        uses: ./.github/actions/docker-scw-deploy
        with:
          secret_key: ${{ secrets.SCW_SECRET_KEY }}
          container_id: 310cc00d-1d59-4c16-93e7-f357e7b42891
          # container_id: ${{ secrets.SCW_ADMIN_CONTAINER_ID }}
