name: Anonymize (CRON)

on:
  workflow_dispatch:
  schedule:
    - cron: "23 2 * * 3" # Every wednesday at 02:23 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  anonymize:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Install clever-tools
        run: npm install -g clever-tools

      - name: Merge production in anonymization
        run: git push --force origin HEAD:anonymization

      - name: Watch deployment
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: ./devops/scripts/cc-watch-deploy.sh ${{ vars.CC_ORGANIZATION_ID }} ${{ vars.CC_APP_ID_PRODUCTION_ANONYMIZATION }} $(git rev-parse HEAD)
