env:
  SUBFOLDER_NAME: api
  APP_NAME: snu-api
  ENVIRONMENT_NAME: snu-api

name: Deploy API (Staging)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Node 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Build lib
        continue-on-error: false
        run: |
          npm ci -w packages/lib
          npm run build -w packages/lib
          rm packages/lib/.gitignore

      - name: Remove DSFR
        run: |
          rm -Rf packages/ds

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Change ssh key file permissions
        run: |
          chmod go-rwx ~/.ssh/id_ed25519

      - name: Remove git folder
        run: |
          rm -rf .git

      - name: Push
        run: |
          git init
          git config user.email "github.deployer@gmail.com"
          git config user.name "Github Deployer"
          git remote add cloudstaging "$CLEVER_CLOUD_GIT_REMOTE_STAGING"
          git add packages ${{ env.SUBFOLDER_NAME }}
          find . -maxdepth 1 -type f -exec git add {} +  # Add first level files
          git commit -m "For deploy"
          git push -f -u cloudstaging master
        env:
          CLEVER_CLOUD_GIT_REMOTE_STAGING: ${{ secrets.CLEVER_CLOUD_GIT_REMOTE_API_STAGING }}
