name: APP - Build Docker image & Deploy Scaleway

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - app/**
#       - packages/**

on:
  push:
    branches:
      - feat-1469-disable

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Node 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Lint code
        working-directory: ${{ env.SUBFOLDER_NAME }}
        continue-on-error: true
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      ACTIVE_HOSTING: ${{ secrets.ACTIVE_HOSTING }}

    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create SSH key
        uses: ./.github/actions/ssh-key
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Get image tag
        id: image_tag
        uses: ./.github/actions/get_image_tag
        with:
          sha: ${{ github.sha }}

      - name: Remove git folder
        run: rm -rf .git

      - name: Docker Build & Publish
        uses: ./.github/actions/build_docker_image
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
          registry: ${{ secrets.SCW_DEV_IMAGE_REGISTRY }}
          image_name: app
          dockerfile_path: app/Dockerfile
          image_tag: ${{ steps.image_tag.outputs.image_tag }}

      # - name: Scaleway container deploy
      #   if: env.ACTIVE_HOSTING == 'scaleway'
      #   uses: ./.github/actions/docker-scw-deploy
      #   with:
      #     secret_key: ${{ secrets.SCW_SECRET_KEY }}
      #     container_id: 3aeb00a1-d6fb-43e9-97b6-a75a29267e9d
      #     # container_id: ${{ secrets.SCW_APP_CONTAINER_ID }}
