name: Synchronise Production (Clever Cloud)
# This action deploys on Clever Cloud the same images that are deployed on Scaleway

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      api_image_tag: ${{ steps.prepare.outputs.api_image_tag }}
      admin_image_tag: ${{ steps.prepare.outputs.admin_image_tag }}
      app_image_tag: ${{ steps.prepare.outputs.app_image_tag }}
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_PROD_DEPLOY_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_PROD_DEPLOY_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: production

      - uses: hashicorp/setup-terraform@v3

      - name: Prepare
        id: prepare
        working-directory: ${{ env.prod_directory }}
        env:
          PG_CONN_STR: ${{ secrets.SCW_PROD_BACKEND_CONN_STR }}
          PGUSER: ${{ secrets.SCW_PROD_BACKEND_USER }}
          PGPASSWORD: ${{ secrets.SCW_PROD_BACKEND_PASSWORD }}
          prod_directory: ./terraform/environments/production
        run: |
          terraform init
          output=$(terraform output -json)

          api_image_tag=$(jq -r '.api_image_tag.value' <<< $output)
          echo "api_image_tag: $api_image_tag"
          echo "api_image_tag=$api_image_tag" >> $GITHUB_OUTPUT

          admin_image_tag=$(jq -r '.admin_image_tag.value' <<< $output)
          echo "admin_image_tag: $admin_image_tag"
          echo "admin_image_tag=$admin_image_tag" >> $GITHUB_OUTPUT

          app_image_tag=$(jq -r '.app_image_tag.value' <<< $output)
          echo "app_image_tag: $app_image_tag"
          echo "app_image_tag=$app_image_tag" >> $GITHUB_OUTPUT

  deploy:
    needs: prepare
    uses: ./.github/workflows/cc-deploy-production.yml
    with:
      api_image_tag: ${{ needs.prepare.outputs.api_image_tag }}
      admin_image_tag: ${{ needs.prepare.outputs.admin_image_tag }}
      app_image_tag: ${{ needs.prepare.outputs.app_image_tag }}
    secrets: inherit
