name: Deploy environment

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      (github.event_name=='pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy')) ||
      (github.event_name=='workflow_dispatch' && github.event.ref != 'production' && github.event.ref != 'main')

    steps:
      - uses: actions/checkout@v4

      - name: Install clever-tools
        run: npm install -g clever-tools

      - name: Create and Start application
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref || github.event.ref }}
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          ./devops/scripts/cc-create-environment.sh ${{ vars.CC_ORGANIZATION_ID }} ${{ vars.CC_APP_ID_CI_SNU_ALL }} ${{ env.BRANCH_NAME }}
          ./devops/scripts/cc-watch-deploy.sh ${{ vars.CC_ORGANIZATION_ID }} ${{ vars.CC_APP_ID_CI_SNU_ALL }} ${{ env.SHA }}
