name: Custom environment - Build Docker image & Deploy Scaleway

on:
  workflow_dispatch:
  push:
    branches:
      - feat-1469

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: [admin, api, app]

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v3

      - id: get_registry
        working-directory: ./terraform/environments/development/project
        env:
          PG_CONN_STR: ${{ secrets.SCW_DEV_BACKEND_CONN_STR }}
          PGUSER: ${{ secrets.SCW_DEV_BACKEND_USER }}
          PGPASSWORD: ${{ secrets.SCW_DEV_BACKEND_PASSWORD }}
        run: |
          terraform init
          terraform output --raw registry_endpoint

      - name: Docker Build & Publish
        uses: ./.github/actions/docker
        with:
          username: nologin
          password: ${{ secrets.SCW_DEV_DEPLOY_SECRET_KEY }}
          registry: ${{ steps.get_registry.outputs.stdout }}
          image_name: ${{ matrix.app_name }}
          dockerfile_path: ${{ matrix.app_name }}/Dockerfile
