name: Destroy environment

on:
  workflow_dispatch:
  delete:
  pull_request:
    types: [ unlabeled ]

defaults:
  run:
    working-directory: devops/scripts

jobs:
  destroy:
    if: |
      (github.event_name=='pull_request' && github.event.label.name == 'deploy')) ||
      ((github.event_name=='delete' || github.event_name=='workflow_dispatch') && github.event.ref != 'production' && github.event.ref != 'main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17"

      - name: Get environment name
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref || github.event.ref }}
        id: env_name
        run: |
          env_name=$(node get-environment-name.js ${{ env.BRANCH_NAME }})
          echo "env_name: $env_name"
          echo "env_name=$env_name" >> $GITHUB_OUTPUT

      - name: Destroy environment
        env:
          SCW_SECRET_KEY: ${{ secrets.SCW_CI_DEPLOY_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        run: node destroy-environment.js ${{ steps.env_name.outputs.env_name }}
