name: Docker Build backup

on:
  push:
    branches:
      - docker-backup

env:
  DOCKER_REGISTRY: ${{ vars.SCW_DOCKER_REGISTRY }}
  RELEASE: ${{ github.sha }}
  ENVIRONMENT: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCW_PROD_DEPLOY_SECRET_KEY }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install clever-tools
        run: npm install -g clever-tools

      # App
      - name: App - Fetch Build Secrets
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: |
          clever env --app ${{ vars.CC_APP_ID_CI_SNU_ALL }} | tail -n +2 > app.env

      - name: App - Build and push
        env:
          APP_NAME: app
        uses: docker/build-push-action@v6
        with:
          push: true
          file: devops/build/docker/Dockerfile.front
          tags: |
            "${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:latest"
            "${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ env.RELEASE }}"
          build-args: |
            "APP_NAME=${{ env.APP_NAME }}"
            "RELEASE=${{ env.RELEASE }}"
            "ENVIRONMENT=${{ env.ENVIRONMENT }}"
          secret-files: |
            "BUILD_SECRETS=./app.env"

      # Admin
      - name: Admin - Fetch Build Secrets
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: |
          clever env --app ${{ vars.CC_APP_ID_CI_SNU_ALL }} | tail -n +2 > admin.env

      - name: Admin - Build and push
        env:
          APP_NAME: admin
        uses: docker/build-push-action@v6
        with:
          push: true
          file: devops/build/docker/Dockerfile.front
          tags: |
            "${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:latest"
            "${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ env.RELEASE }}"
          build-args: |
            "APP_NAME=${{ env.APP_NAME }}"
            "RELEASE=${{ env.RELEASE }}"
            "ENVIRONMENT=${{ env.ENVIRONMENT }}"
          secret-files: |
            "BUILD_SECRETS=./admin.env"

      # Api
      - name: Api - Fetch Build Secrets
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: |
          clever env --app ${{ vars.CC_APP_ID_CI_SNU_ALL }} | tail -n +2 > api.env

      - name: Api - Build and push
        env:
          APP_NAME: api
        uses: docker/build-push-action@v6
        with:
          push: true
          file: devops/build/docker/Dockerfile.api
          tags: |
            "${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:latest"
            "${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ env.RELEASE }}"
          build-args: |
            "APP_NAME=${{ env.APP_NAME }}"
            "RELEASE=${{ env.RELEASE }}"
            "ENVIRONMENT=${{ env.ENVIRONMENT }}"
          secret-files: |
            "BUILD_SECRETS=./api.env"

      # ApiV2
      - name: ApiV2 - Fetch Build Secrets
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: |
          clever env --app ${{ vars.CC_APP_ID_CI_SNU_ALL }} | tail -n +2 > apiv2.env

      - name: ApiV2 - Build and push
        env:
          APP_NAME: apiv2
        uses: docker/build-push-action@v6
        with:
          push: true
          file: devops/build/docker/Dockerfile.apiv2
          tags: |
            "${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:latest"
            "${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ env.RELEASE }}"
          build-args: |
            "APP_NAME=${{ env.APP_NAME }}"
            "RELEASE=${{ env.RELEASE }}"
            "ENVIRONMENT=${{ env.ENVIRONMENT }}"
          secret-files: |
            "BUILD_SECRETS=./apiv2.env"