name: Docker Build backup

on:
  push:
    branches:
      - docker-backup

env:
  DOCKER_REGISTRY: rg.fr-par.scw.cloud/snu-staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCW_PROD_DEPLOY_SECRET_KEY }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install clever-tools
        run: npm install -g clever-tools

      - name: App - Fetch Build Secrets
        id: secrets
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: |
          secrets=$(clever env --app ${{ vars.CC_APPLICATION_ID_CI }})
          echo "secrets=$secrets" >> $GITHUB_OUTPUT

      - name: App - Build and push
        env:
          APP_NAME: app
        uses: docker/build-push-action@v6
        with:
          push: true
          file: devops/build/docker/Dockerfile.front
          tags: |
            "${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:latest"
            "${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}"
          build-args: |
            "APP_NAME=${{ env.APP_NAME }}"
            "RELEASE=${{ github.sha }}"
            "ENVIRONMENT=ci"
          secrets: |
            "BUILD_SECRETS=${{ steps.secrets.outputs.secrets }}"
          # secret-files: |
          #   "BUILD_SECRETS=./build.env"