name: Mirroring

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirroring
        uses: rebasing-xyz/checkout-and-sync@v1
        with:
          source-repo: "git@github.com:betagouv/service-national-universel.git"
          destination-repo: "git@github.com:michaelgarcia75/snu-mirror.git"
          ssh-private-key: ${{ secrets.MIROIR_SSH_KEY }}
