name: Mirroring

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          ssh_private_key: ${{ secrets.MIROIR_SSH_KEY }}
          source_repo: "git@github.com:betagouv/service-national-universel.git"
          target_repo_url: "git@github.com:michaelgarcia75/snu-mirror.git"
          ssh_username: "git"
