name: Mirroring

on:
  push:
    branches: [production_state]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Git LFS objects
        run: git lfs fetch --all

      - name: Remove .github directory
        run: rm -rf .github

      - name: Mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          ssh_private_key: ${{ secrets.MIROIR_SSH_KEY }}
          target_repo_url: "git@github.com:selego/snu-mirror.git"
          ssh_username: "git"
