name: Test RT

on:
  push:
    branches:
      - watch-prod-deploy

env:
  PROD_ENV_NAME: production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          while read row; do
              echo "$row started"
              duration=$((RANDOM / 1000)) && echo "$row $duration" && sleep $duration && echo "$row ended" &
          done <<EOF
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_API }}
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_APIV2 }}
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_APP }}
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_ADMIN }}
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_TASKS }}
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_TASKSV2 }}
          EOF

          wait