name: Test RT

on:
  push:
    branches:
      - watch-prod-deploy

env:
  PROD_ENV_NAME: production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install clever-tools
        run: npm install -g clever-tools

      - name: Test
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: |
          while read row; do
            ./devops/scripts/cc-watch-deploy.sh  ${{ vars.CC_ORGANIZATION_ID }} $row ${{ github.sha }} &
          done <<EOF
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_API }}
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_APIV2 }}
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_APP }}
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_ADMIN }}
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_TASKS }}
          ${{ vars.CC_APP_ID_PRODUCTION_SNU_TASKSV2 }}
          EOF

          wait