name: Test RT

on:
  push:
    branches:
      - poc_rt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Merge main in deploy-ci
        run: |
          git remote -v
          git push --force origin poc_rt:deploy-ci