name: Test RT

on:
  push:
    branches:
      - poc_rt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Merge main in deploy-ci
        run: |
          git remote -v
          git push --force origin poc_rt:deploy-ci

      - name: Install clever-tools
        run: npm install -g clever-tools

      - name: Watch deployment
        env:
          ORGANIZATION_ID: ${{ vars.CC_ORGANIZATION_ID }}
          APPLICATION_ID: ${{ vars.CC_APPLICATION_ID_CI }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: ./devops/scripts/cc-watch-deploy.sh