name: Test Release Changelog

on:
  push:
    branches:
      - 2214_release_changelog

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      main_sha: ${{ steps.prepare.outputs.main_sha }}
      production_sha: ${{ steps.prepare.outputs.production_sha }}

    steps:

    - uses: actions/checkout@v4

    - name: Prepare
      id: prepare
      run : |
        git fetch origin main production
        main_sha=$(git rev-parse origin/main)
        echo "main_sha: $main_sha"
        echo "main_sha=$main_sha" >> $GITHUB_OUTPUT

        production_sha=$(git rev-parse origin/production)
        echo "production_sha: $production_sha"
        echo "production_sha=$production_sha" >> $GITHUB_OUTPUT

    - name: "print changelog"
      id: changelog
      run : |
        echo "<https://github.com/betagouv/service-national-universel/compare/${{ steps.prepare.outputs.production_sha }}...${{ steps.prepare.outputs.main_sha }}|Release du $(date -Idate)>" > CHANGELOG.md
        git log --pretty="• %s" "${{ steps.prepare.outputs.production_sha }}...${{ steps.prepare.outputs.main_sha }}" \
          | grep --invert-match "chore(release): version" \
          | sort \
          | sed 's #\([0-9]*\) <https://github.com/betagouv/service-national-universel/pull/\1|#\1> g' \
          >> CHANGELOG.md
        cat CHANGELOG.md
        {
          echo 'changelog<<EOF'
          cat CHANGELOG.md
          echo EOF
        } >> "$GITHUB_OUTPUT"

    # - name: debug
    #   run : echo ${{ steps.changelog.outputs.changelog }}

    - name: Slack Post
      uses: slackapi/slack-github-action@v1.25.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
        channel-id: '#test-rt'
        # For posting a simple plain text message
        slack-message: "${{ steps.changelog.outputs.changelog }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
