name: Test RT

on:
  push:
    branches:
      - poc_rt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install clever-tools
        run: npm install -g clever-tools

      - name: Merge main in deploy-ci
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: |
          clever link app_9f11ed0e-0f52-4e94-8744-a61c2aa3fdc2
          clever deploy

      # - name: Merge main in deploy-ci
      #   run: |
      #     git remote -v
      #     git push --force origin poc_rt:deploy-ci