name: Test RT

on:
  workflow_dispatch:
  push:
    branches:
      - tmp-rt-no-ci

defaults:
  run:
    working-directory: devops/scripts

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20"

      - name: Destroy Environment
        env:
          SCW_SECRET_KEY: ${{ secrets.SCW_CI_DEPLOY_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        run: node destroy-environment.js snu-custom 1970-breadcrumb
