name: Test and deploy CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 3577-app # TODO : remove

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CI_ENV_NAME: ci

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.registry.outputs.registry }}
      build_matrix: ${{ steps.build.outputs.tags }}
      test_matrix: ${{ steps.test.outputs.tests }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20"

      - name: Get registry
        id: registry
        working-directory: devops/scripts
        env:
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
          SCW_SECRET_KEY: ${{ secrets.SCW_CI_DEPLOY_SECRET_KEY }}
        run: |
          registry=$(node get-environment-registry.js ${{ env.CI_ENV_NAME }})
          echo "registry: $registry"
          echo "registry=$registry" >> $GITHUB_OUTPUT

      - name: Get build configuration
        id: build
        run: |
          echo "[]" \
          | jq  '. + [{name:"api", tag:$tag}]' --arg tag "$(git log --max-count=1 --oneline -- api packages/lib package-lock.json | cut -d " " -f 1)" \
          | jq  '. + [{name:"apiv2", tag:$tag}]' --arg tag "$(git log --max-count=1 --oneline -- apiv2 packages/lib package-lock.json | cut -d " " -f 1)" \
          | jq  '. + [{name:"app", tag:$tag}]' --arg tag "$(git log --max-count=1 --oneline -- app packages package-lock.json | cut -d " " -f 1)" \
          | jq  '. + [{name:"admin", tag:$tag}]' --arg tag "$(git log --max-count=1 --oneline -- admin packages package-lock.json | cut -d " " -f 1)" > tags.json

          cat tags.json
          echo "tags=$(jq -c < tags.json)" >> $GITHUB_OUTPUT

      - name: Get test configuration
        id: test
        run: |
          echo "[]" \
          | jq  '. + [{name:"api"}]' \
          | jq  '. + [{name:"apiv2"}]' \
          | jq  '. + [{name:"app"}]' \
          | jq  '. + [{name:"admin"}]' \
          | jq  '. + [{name:"lib"}]' > tests.json

          cat tests.json
          echo "tests=$(jq -c < tests.json)" >> $GITHUB_OUTPUT

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJSON(needs.prepare.outputs.test_matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Run tests
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ./.github/actions/run-tests-${{matrix.app.name}}
          with: '{"branch_name": "${{ github.ref_name }}", "CC_TEST_REPORTER_ID": "${{ secrets.CC_TEST_REPORTER_ID }}" }'

  build:
    needs: [prepare, test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJSON(needs.prepare.outputs.build_matrix) }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          username: nologin
          password: ${{ secrets.SCW_CI_DEPLOY_SECRET_KEY }}
          registry: ${{ needs.prepare.outputs.registry }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20"

      - name: Build image
        working-directory: devops/scripts
        env:
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
          SCW_SECRET_KEY: ${{ secrets.SCW_CI_DEPLOY_SECRET_KEY }}
        run: |
          node build-application-docker.js ${{ env.CI_ENV_NAME }} ${{matrix.app.name}} ${{matrix.app.tag}}

      - name: Push image
        run: |
          docker push ${{ needs.prepare.outputs.registry }}/${{matrix.app.name}}:${{matrix.app.tag}}

  deploy:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJSON(needs.prepare.outputs.build_matrix) }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20"

      # - name: Deploy image on Scaleway
      #   working-directory: devops/scripts
      #   env:
      #     SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
      #     SCW_SECRET_KEY: ${{ secrets.SCW_CI_DEPLOY_SECRET_KEY }}
      #   run: |
      #     node deploy-scaleway.js ${{ env.CI_ENV_NAME }} ${{matrix.app.name}} ${{matrix.app.tag}}
